import type { KQuizSet } from './model'

type Block = { type: 'h2' | 'h3' | 'li' | 'p'; text: string }

/** Mirrors KQuizGuide's own markdown-lite parsing (heading/bullet/paragraph blocks, **bold** spans)
 * so the PDF keeps the same structure the on-screen study guide shows -- bold spans are flattened to
 * plain text rather than mixed-run bold, which jsPDF doesn't support without manual run layout. */
function parseBlocks(text: string): Block[] {
  const strip = (s: string) => s.replace(/\*\*([^*]+)\*\*/g, '$1')
  const blocks: Block[] = []
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim()
    if (!line) continue
    const h2 = /^#{1,2}\s+(.*)$/.exec(line)
    const h3 = /^#{3,6}\s+(.*)$/.exec(line)
    const li = /^[-*]\s+(.*)$/.exec(line)
    if (h2) blocks.push({ type: 'h2', text: strip(h2[1]) })
    else if (h3) blocks.push({ type: 'h3', text: strip(h3[1]) })
    else if (li) blocks.push({ type: 'li', text: strip(li[1]) })
    else blocks.push({ type: 'p', text: strip(line) })
  }
  return blocks
}

/** Renders a K-Quiz study set's AI summary/study guide as a downloadable PDF -- built entirely in the
 * browser (jsPDF is loaded lazily so it never bloats the main bundle), matching how everything else in
 * KONO stays on-device unless a person explicitly exports or shares it. */
export async function buildKQuizSetPdf(set: KQuizSet, subjectName: string): Promise<Blob> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'letter' })
  const marginX = 54, maxWidth = 612 - marginX * 2, pageBottom = 740
  let y = 64
  const ensureSpace = (needed: number) => { if (y + needed > pageBottom) { doc.addPage(); y = 64 } }
  const writeLines = (lines: string[], lineHeight: number) => {
    for (const line of lines) { ensureSpace(lineHeight); doc.text(line, marginX, y); y += lineHeight }
  }

  doc.setFont('helvetica', 'bold'); doc.setFontSize(18)
  writeLines(doc.splitTextToSize(set.title, maxWidth), 22)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(110)
  const meta = (subjectName ? subjectName + ' · ' : '') + new Date(set.createdAt).toLocaleDateString()
  writeLines(doc.splitTextToSize(meta, maxWidth), 14)
  doc.setTextColor(0)
  y += 8

  const renderSection = (heading: string, text: string) => {
    if (!text) return
    ensureSpace(26)
    doc.setFont('helvetica', 'bold'); doc.setFontSize(14)
    writeLines([heading], 20)
    y += 2
    for (const block of parseBlocks(text)) {
      if (block.type === 'h2') { doc.setFont('helvetica', 'bold'); doc.setFontSize(13); ensureSpace(18); writeLines(doc.splitTextToSize(block.text, maxWidth), 17) }
      else if (block.type === 'h3') { doc.setFont('helvetica', 'bold'); doc.setFontSize(11.5); ensureSpace(16); writeLines(doc.splitTextToSize(block.text, maxWidth), 15) }
      else if (block.type === 'li') { doc.setFont('helvetica', 'normal'); doc.setFontSize(11); const wrapped = doc.splitTextToSize('•  ' + block.text, maxWidth - 14) as string[]; writeLines(wrapped.map((l, i) => i === 0 ? l : '   ' + l), 14) }
      else { doc.setFont('helvetica', 'normal'); doc.setFontSize(11); writeLines(doc.splitTextToSize(block.text, maxWidth), 14) }
    }
    y += 10
  }

  renderSection('Summary', set.summary ?? '')
  renderSection('Study guide', set.studyGuide ?? '')

  doc.setFont('helvetica', 'italic'); doc.setFontSize(9); doc.setTextColor(140)
  ensureSpace(30)
  writeLines(doc.splitTextToSize('Generated by AI from your own notes — check it against the original material.', maxWidth), 12)

  return doc.output('blob')
}

/** Exposed for tests. */
export const __test__ = { parseBlocks }
