// Generated by tools/draw_halloween_night.py; do not edit by hand.
/** The October island's full moon (0..1 across the map; r is the radius over the map's width), so the
 * island can glow it. */
export const HALLOWEEN_MOON={"x":0.7900,"y":0.1500,"r":0.0620} as const
