// Generated by tools/import_halloween_island.py; do not edit by hand.
/** The October island's full moon in its night picture (0..1 across the map; r is the radius over the
 * map's width), so the island can glow it and send bats past it. */
export const HALLOWEEN_MOON={"x": 0.1744, "y": 0.068, "r": 0.0355} as const
