// Generated by tools/draw_kono_outfits.py from the KONO sprites; don't edit by hand. Re-run the script after
// changing a pose or an outfit.
export type OutfitFit={px:[number,number];sink:number;nudge:number;full?:boolean;skip?:string[]}
export type PoseHead={x:number;y:number;w:number;size:[number,number]}
/** Where KONO's head is in each pose (shares of the image): top centre, and the head's width. */
export const POSE_HEADS:Record<string,PoseHead>={
  'excited': {x: 0.5189, y: 0.0575, w: 0.7311, size: [238, 226]},
  'fishing': {x: 0.3614, y: 0.0324, w: 0.5361, size: [332, 247]},
  'happy': {x: 0.5148, y: 0.0594, w: 0.7511, size: [237, 219]},
  'idle': {x: 0.5235, y: 0.0619, w: 0.7393, size: [234, 226]},
  'pond': {x: 0.5057, y: 0.0, w: 0.6122, size: [294, 246]},
  'question': {x: 0.4765, y: 0.0359, w: 0.7746, size: [213, 195]},
  'read': {x: 0.5166, y: 0.0505, w: 0.7601, size: [271, 277]},
  'sit': {x: 0.4482, y: 0.052, w: 0.8495, size: [299, 269]},
  'sleep': {x: 0.6848, y: 0.0698, w: 0.6292, size: [240, 172]},
  'tea': {x: 0.4482, y: 0.052, w: 0.8495, size: [299, 269]},
  'walk-down-01': {x: 0.5045, y: 0.0591, w: 0.7143, size: [224, 220]},
  'walk-down-02': {x: 0.5134, y: 0.0631, w: 0.7098, size: [224, 222]},
  'walk-down-03': {x: 0.5045, y: 0.0591, w: 0.7143, size: [224, 220]},
  'walk-left-01': {x: 0.4474, y: 0.0651, w: 0.7464, size: [209, 215]},
  'walk-left-02': {x: 0.4375, y: 0.0645, w: 0.763, size: [211, 217]},
  'walk-right-01': {x: 0.5338, y: 0.0341, w: 0.8137, size: [204, 205]},
  'walk-right-02': {x: 0.5349, y: 0.0341, w: 0.8213, size: [207, 205]},
  'walk-up-01': {x: 0.5037, y: 0.0352, w: 0.7156, size: [225, 199]},
  'walk-up-02': {x: 0.4808, y: 0.0355, w: 0.7064, size: [218, 197]},
  'walk-up-03': {x: 0.5037, y: 0.0352, w: 0.7156, size: [225, 199]},
}
/** Each outfit's size in sprite pixels (drawn at KONO's own pixel size), how far it sinks into the fluffy
 * top (share of its height) and any sideways nudge (share of the head's width). */
export const OUTFIT_FITS:Record<string,OutfitFit>={
  headband: {px: [184, 64], sink: 0.62, nudge: 0},
  beanie: {px: [144, 104], sink: 0.48, nudge: 0},
  sunhat: {px: [200, 88], sink: 0.38, nudge: 0},
  gradcap: {px: [176, 96], sink: 0.4, nudge: 0},
  flowers: {px: [184, 56], sink: 0.55, nudge: 0},
  wizard: {px: [160, 144], sink: 0.22, nudge: 0},
  crown: {px: [120, 72], sink: 0.4, nudge: 0},
  bow: {px: [112, 64], sink: 0.45, nudge: 0.26},
  chef: {px: [136, 120], sink: 0.3, nudge: 0},
  witch: {px: [176, 144], sink: 0.22, nudge: 0},
  ghost: {px: [0, 0], sink: 0, nudge: 0, full: true, skip: ["pond"]},
  frankenstein: {px: [0, 0], sink: 0, nudge: 0, full: true, skip: ["pond"]},
}
/** Costumes drawn for each pose (a ghost sheet, Frankenstein's hair) have 24px of room all round. */
export const COSTUME_PAD=24
/** Poses where KONO isn't wearing an outfit: asleep, and fishing (that pose has its own straw hat). */
export const NO_OUTFIT_POSES=new Set(['sleep','fishing'])
/** The outfit's box on a pose, in that pose's pixels (same maths as the drawing script's preview). */
export function outfitBox(pose:string,outfit:string):{x:number;y:number;w:number;h:number}|null{
 const head=POSE_HEADS[pose],fit=OUTFIT_FITS[outfit]
 if(!head||!fit||NO_OUTFIT_POSES.has(pose)||fit.skip?.includes(pose))return null
 const [w,h]=head.size,[ow,oh]=fit.px
 if(fit.full)return {x:-COSTUME_PAD,y:-COSTUME_PAD,w:w+2*COSTUME_PAD,h:h+2*COSTUME_PAD}
 const cx=head.x*w+fit.nudge*head.w*w
 const y=head.y*h+0.10*head.w*w-oh*(1-fit.sink)
 return {x:cx-ow/2,y,w:ow,h:oh}
}
/** The image for an outfit on a pose: one drawing for hats, one per pose for costumes. */
export const outfitSrcFor=(outfit:string,pose:string)=>'/garden/kono/outfits/'+(OUTFIT_FITS[outfit]?.full?outfit+'/'+pose:outfit)+'.webp'
