import { useState, type FormEvent } from 'react'
import type { AdminAccount, SupportActivity } from '../store/supabaseRemote'
import type { usePlannerRepository } from '../store/repository'
import { type AppData, localDate } from '../store/model'
import {APP_VERSION} from '../version'
type Store=ReturnType<typeof usePlannerRepository>
export function SaveStatus({store}:{store:Store}){
 // Routine "Saved…" states are quiet (hidden on small screens); anything needing attention always shows.
 const quiet=!store.error&&!store.support&&/^(Saved on this device|Saved to your account|Saved|Account ready)$/.test(store.status)
 return <div className={'save-status'+(quiet?' is-quiet':'')}><small>Build {APP_VERSION.split('production-')[1]} · </small><span role="status"><span className="save-status-account">{store.support?'Helping: '+store.support.email:store.user?'Account: '+store.user.email:'This device only'} · </span>{store.status}</span>{store.error&&<p role="alert">{store.error} <button onClick={store.repository.export}>Export working copy</button> <button onClick={store.repository.retry}>Retry</button></p>}</div>
}
export function AccountPanel({store}:{store:Store}){
 const {repository}=store
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[signInSent,setSignInSent]=useState(false)
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Could not finish. Your working copy is preserved.')}finally{setBusy(false)}}
 return <section className="card account-panel" id="account-data"><span className="eyebrow">Account & data</span><h2>Your work, safely kept</h2><p>{store.user?'Your signed-in account owns these plans. Each device keeps a recovery cache.':'Local plans stay in this browser. Sign in to keep your own plans across devices.'}</p><SaveStatus store={store}/>{!store.user&&(repository.signInProvider==='email'?<form className="email-sign-in" onSubmit={e=>{e.preventDefault();void action(async()=>{await repository.signInWithEmail(email);setSignInSent(true)})}}><label>Email address<input required type="email" autoComplete="email" maxLength={320} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="primary" disabled={busy}>{busy?'Sending…':'Email me a sign-in link'}</button>{signInSent&&<p role="status">Check your email and open the KONO sign-in link on this device.</p>}</form>:<a className="primary button-link" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>)}<div className="account-actions"><button onClick={repository.retry} disabled={busy}>Retry saving</button>{store.user&&<button disabled={busy} onClick={()=>{if(window.confirm('Sign out and clear this account’s cached plan from this browser? Unsynced work must be saved first.'))void action(repository.signOut)}}>Sign out</button>}</div>
 {store.needsMigration&&<div className="recovery-notice"><h3>Bring this device’s plan to your account?</h3><p>Nothing is uploaded until you choose. Import only if these plans belong to you.</p><button onClick={()=>{if(window.confirm('These local plans belong to me. Copy them to my signed-in account?'))repository.importLegacy()}}>Import my local plans</button><button onClick={repository.skipMigration}>Start a separate account plan</button></div>}
 {store.recovery.map(file=><div className="recovery-notice" key={file.name}><p>{file.reason}</p><button onClick={()=>repository.downloadRecovery(file)}>Download original recovery file</button></div>)}
 {!!store.conflicts.length&&<div className="recovery-notice"><h3>Two copies need your attention</h3><p>No conflicting edits have been overwritten. Export your working copy, then choose the saved cloud copy. You can reapply your changes afterward.</p><button onClick={repository.export}>Export this working copy</button><button disabled={busy} onClick={()=>{if(window.confirm('Replace the working copy with the cloud version? Export first to keep your changes.'))void action(repository.useCloud)}}>Use cloud copy</button></div>}
 {store.user&&<details className="danger-zone"><summary>Delete cloud study data</summary><p>Deletes your KONO plans and cloud revision history. This does not delete your sign-in account. Export a backup first.</p><button disabled={busy} onClick={()=>{if(window.prompt('Type DELETE to erase your cloud study data and this account’s local cache.')==='DELETE')void action(repository.deleteAccountData)}}>Delete cloud study data</button></details>}
 
 <p><strong>One account per person.</strong> Study profiles organize your own terms or plans; they are not separate private logins. Sign out before another person uses a shared device. Local-only mode is shared by people using the same browser profile and does not sync to another phone.</p><details><summary>Privacy & storage</summary><p>KONO stores study plans, notes, settings and Sanctuary progress. Signed-in data is kept in this site’s database and a browser recovery cache; local mode stays on this device. Export a backup before clearing browser data. Interface fonts are requested from Google Fonts. Only enable live weather if you want your entered location sent to Open-Meteo. Music starts only when you press play. No advertising or analytics tracker is included.</p><p>Signed-in plans are backed up automatically each time you open KONO (the 30 most recent copies are kept). KONO support can open a signed-in account’s plan to help fix a problem. Every time that happens it is logged, and you can see it under Settings › Import & export › Backups › Support activity. Deleting your cloud study data also deletes its backups.</p><p>Sign out on shared computers. A downloaded backup contains your study information: keep it somewhere private.</p></details>{error&&<p role="alert">{error}</p>}</section>
}
/** Export a backup, review and restore one, and download recovery snapshots. */
export function BackupPanel({store}:{store:Store}){
 const {repository}=store
 const [candidate,setCandidate]=useState<AppData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [history,setHistory]=useState<{revision:number;created_at:string;bySupport?:boolean}[]>([])
 const [autoBackups,setAutoBackups]=useState<{revision:number;created_at:string;reason:'open'|'before-support'}[]|null>(null),[activity,setActivity]=useState<SupportActivity[]|null>(null)
 const cloud=!!store.user&&!store.support
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Could not finish. Your working copy is preserved.')}finally{setBusy(false)}}
 return <section className="card account-panel"><h3>Backups</h3><p>Download everything in one file, or restore from one. A backup contains your study information: keep it somewhere private.</p><div className="account-actions"><button onClick={repository.export}>Export backup</button><label className="button-link">Import backup<input type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>8_000_000){setError('Backup is too large. The limit is 8 MB.');return}void file.text().then(raw=>{try{setCandidate(repository.importPreview(raw));setError('')}catch(error){setError(error instanceof Error?error.message:'Invalid backup')}})}}/></label></div>{error&&<p role="alert">{error}</p>}
 {candidate&&<div className="recovery-notice"><h3>Review backup before replacing</h3><p>{candidate.profiles.length} plans · {candidate.tasks.length} assignments · {candidate.notes.length} notes · {candidate.exams.length} exams</p><p>This replaces the plans currently open here. Export your current work first.</p><button onClick={()=>{if(window.confirm('Replace the current plans with this backup?')){repository.replace(candidate);setCandidate(null)}}}>Use this backup</button><button onClick={()=>setCandidate(null)}>Cancel</button></div>}
 {repository.deviceCopy()&&!store.needsMigration&&<p className="recovery-notice">This browser also has a plan that was saved here before you signed in. <button type="button" onClick={()=>{const copy=repository.deviceCopy();if(copy)repository.downloadBackup(copy)}}>Download that plan</button> Then use Import backup to review it and bring it into your account.</p>}
 <details><summary>Recovery snapshots</summary><p>The five most recent device copies and up to twenty cloud revisions are retained. Download a snapshot, then use Import backup to review it before restoring.</p>{repository.localBackups().map((data,i)=><button key={i} onClick={()=>repository.downloadBackup(data)}>Download device copy {i+1}</button>)}{cloud&&<><button disabled={busy} onClick={()=>void action(async()=>{setHistory(await repository.cloudHistory())})}>Show cloud history</button><ul>{history.map(item=><li key={item.revision}><button disabled={busy} onClick={()=>void action(()=>repository.downloadCloudBackup(item.revision))}>Download revision {item.revision}</button> · {new Date(item.created_at).toLocaleString()}{item.bySupport&&' · changed by KONO support'}</li>)}</ul></>}</details>
 {cloud&&<details><summary>Automatic backups</summary><p>Each time you open KONO, a copy of your saved plan is kept (skipped when nothing changed). The 30 most recent are kept. Download one, then use Import backup to review it before restoring.</p><button disabled={busy} onClick={()=>void action(async()=>{setAutoBackups(await repository.autoBackups())})}>Show automatic backups</button>{autoBackups&&(autoBackups.length?<ul>{autoBackups.map(item=><li key={item.revision}><button disabled={busy} onClick={()=>void action(()=>repository.downloadAutoBackup(item.revision))}>Download</button> {new Date(item.created_at).toLocaleString()} · {item.reason==='before-support'?'kept before KONO support helped':'when you opened KONO'}</li>)}</ul>:<p>No automatic backups yet. One is kept the next time you open KONO after saving.</p>)}</details>}
 {cloud&&<details><summary>Support activity</summary><p>KONO support can open your plan to help fix a problem. Every view and change is listed here.</p><button disabled={busy} onClick={()=>void action(async()=>{setActivity(await repository.supportActivity())})}>Show support activity</button>{activity&&(activity.length?<ul>{activity.map(item=><li key={item.id}>{new Date(item.createdAt).toLocaleString()} · KONO support {item.action==='edit'?'changed your plan':'opened your plan'}</li>)}</ul>:<p>KONO support has never opened your plan.</p>)}</details>}</section>
}
/** Shown instead of the welcome screen when saved data exists but this build couldn't read it. */
export function RecoveryScreen({store}:{store:Store}){
 const [status,setStatus]=useState('')
 const download=async()=>{setStatus('');try{setStatus(await store.repository.downloadUnreadable()?'Downloaded. Keep that file somewhere safe.':'')}catch{setStatus('Could not prepare the download. Your data is still in this browser.')}}
 return <main className="onboarding page-stack"><section className="card recovery-screen" role="alert"><span className="eyebrow">KONO</span><h1>We couldn't open your saved plan</h1>
  <p><strong>Your data is safe.</strong> Nothing has been changed or deleted, and KONO won't save over it while this screen is showing.</p>
  <p>This can happen right after an update. Trying again often fixes it. If it doesn't, download a copy so nothing can be lost, then check back after the next update.</p>
  <div className="account-actions"><button className="primary" onClick={()=>window.location.reload()}>Try again</button><button onClick={()=>void download()}>Download a copy of my data</button>{store.recovery.filter(file=>file.raw).map(file=><button key={file.name} onClick={()=>store.repository.downloadRecovery(file)}>Download older copy ({file.name})</button>)}</div>
  {status&&<p role="status">{status}</p>}
  {store.error&&<details><summary>Technical details</summary><p>{store.error}</p></details>}
 </section></main>
}
/** Email sign-in link form, shared by onboarding, the save-to-email banner and Settings. */
/** Turns a sign-in email failure into plain words; rate limits and outages aren't the person's fault. */
function signInProblem(err:unknown){
 const raw=err instanceof Error?err.message:''
 if(/rate limit|too many|429|over_email_send_rate/i.test(raw))return {text:'KONO has sent a lot of sign-in emails in the last hour, so this one is waiting its turn. Try again in a little while.',service:true}
 if(/fetch|network|failed to|timeout|smtp|sending|unexpected|500|503/i.test(raw)||!raw)return {text:'We couldn’t send the email right now. Check your connection and try again in a moment.',service:true}
 return {text:raw,service:false}
}
export function EmailSignIn({store,button='Email me a sign-in link',onUseDevice}:{store:Store;button?:string;onUseDevice?:()=>void}){
 const [email,setEmail]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState<{text:string;service:boolean}|null>(null)
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError(null);try{await store.repository.signInWithEmail(email);setSent(true)}catch(err){setError(signInProblem(err))}finally{setBusy(false)}}
 return <form className="email-sign-in" onSubmit={e=>void submit(e)}><label>Email address<input required type="email" autoComplete="email" maxLength={320} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="primary" disabled={busy}>{busy?'Sending…':button}</button>{sent&&<p role="status">Check your email for a link from KONO and open it on this device. It can take a minute; check spam if it doesn’t arrive.</p>}{error&&<p role="alert">{error.text}{error.service&&onUseDevice&&<> <button type="button" className="sign-in-fallback" onClick={onUseDevice}>Start on this device for now</button> <small>You can save it to your email later from the banner at the top.</small></>}</p>}</form>
}
export function Onboarding({store}:{store:Store}){
 const profile=store.data.profiles[0], [name,setName]=useState(''),[label,setLabel]=useState('My study plan'),[deviceStart,setDeviceStart]=useState(false)
 const submit=(e:FormEvent)=>{e.preventDefault();if(!name.trim()||!label.trim())return;store.repository.update(d=>({...d,onboardingComplete:true,profiles:d.profiles.map(p=>p.id===profile.id?{...p,name:name.trim(),label:label.trim()}:p)}))}
 const demo=()=>void store.repository.update(d=>({...d,onboardingComplete:true,notes:[...d.notes,{id:'demo-note-'+profile.id,profileId:profile.id,subjectId:'',title:'Welcome to your board',body:'Edit this note, change its color, or move it to Trash. Your own work starts here.',created:new Date().toISOString(),pinned:true}],tasks:[...d.tasks,{id:'demo-task-'+profile.id,profileId:profile.id,subjectId:'',title:'Try completing an assignment',due:localDate(),done:false,notes:'This optional demo task can be edited, reopened, or removed.'}]}))
 // Plans live in an account tied to your email, so they can't be lost with a browser. The demo stays on this device.
 if(store.repository.signInProvider==='email'&&!store.user&&!deviceStart)return <main className="onboarding page-stack"><section className="card"><span className="eyebrow">Welcome to KONO</span><h1>A little space for steady progress.</h1><p>Sign in with your email to start your plan. It’s saved to your account, backed up automatically every time you open KONO, and there on any device you sign in on. No password: we email you a link.</p><EmailSignIn store={store} button="Email me a link to start" onUseDevice={()=>setDeviceStart(true)}/><p className="onboarding-demo">Just looking around? <button type="button" onClick={demo}>Try a small demo instead</button> <small>The demo is saved on this device only.</small></p></section></main>
 return <main className="onboarding page-stack"><form className="card" onSubmit={submit}><span className="eyebrow">Welcome to KONO</span><h1>A little space for steady progress.</h1>{store.user&&<p className="onboarding-account">Signed in as <strong>{store.user.email}</strong>. Your plan saves to this account.</p>}<p>Start with your own plan. Add subjects, small assignments and notes; your Sanctuary grows as you finish work.</p><label>Your name<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)} autoComplete="given-name"/></label><label>Plan name<input required maxLength={200} value={label} onChange={e=>setLabel(e.target.value)}/></label><button className="primary" disabled={store.needsMigration}>Create my study plan</button><button type="button" disabled={store.needsMigration} onClick={demo}>Try a small demo instead</button></form><AccountPanel store={store}/></main>
}
const SNOOZE_KEY='kono-save-to-email-snoozed-until'
/** Top-of-page account notices: who you're helping in support mode, or a nudge to save a device-only plan to an email account. */
export function AccountBanners({store}:{store:Store}){
 const [snoozed,setSnoozed]=useState(()=>{try{return Number(localStorage.getItem(SNOOZE_KEY)??0)>Date.now()}catch{return false}})
 const [error,setError]=useState('')
 if(store.support)return <div className="support-banner" role="status"><p><strong>KONO support:</strong> you’re working in <strong>{store.support.email}</strong>’s plan. Changes save to their account, and they can see that support opened and changed it.</p><button type="button" onClick={()=>{setError('');store.repository.exitSupport().catch(e=>setError(e instanceof Error?e.message:'Could not exit yet.'))}}>Exit support</button>{error&&<p role="alert">{error}</p>}</div>
 if(!store.ready||store.user||snoozed||store.repository.signInProvider!=='email')return null
 const snooze=()=>{try{localStorage.setItem(SNOOZE_KEY,String(Date.now()+86_400_000))}catch{/* storage unavailable */}setSnoozed(true)}
 return <section className="save-to-email-banner" aria-label="Save your plan to your email"><p><strong>Your plan is only saved in this browser.</strong> If this browser’s data is cleared, it’s gone. Save it to your email so it’s backed up and on every device you sign in on.</p><EmailSignIn store={store} button="Save to my email"/><button type="button" className="save-to-email-later" onClick={snooze}>Remind me tomorrow</button></section>
}
const when=(value:string|null)=>value?new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'never'
/** KONO support: every account, and a way to open one to help. The server re-checks support access on every call. */
export function SupportAdminPanel({store}:{store:Store}){
 const {repository}=store
 const [accounts,setAccounts]=useState<AdminAccount[]|null>(null),[activity,setActivity]=useState<SupportActivity[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{setBusy(true);setError('');try{const [list,log]=await Promise.all([repository.adminAccounts(),repository.adminActivity()]);setAccounts(list);setActivity(log)}catch(e){setError(e instanceof Error?e.message:'Could not load accounts.')}finally{setBusy(false)}}
 const emailOf=(id:string|null)=>id?accounts?.find(a=>a.userId===id)?.email??'an account':'a removed account'
 const needle=query.trim().toLowerCase()
 const shown=(accounts??[]).filter(a=>!needle||[a.email,a.profiles,a.username??''].some(v=>v.toLowerCase().includes(needle)))
 const open=(account:AdminAccount)=>{if(!window.confirm(`Open ${account.email}’s plan to help?\n\nA backup is kept first. What you view and change is logged, and they can see it.`))return;try{repository.startSupport({id:account.userId,email:account.email})}catch(e){setError(e instanceof Error?e.message:'Could not open that account.')}}
 return <section className="card account-panel support-admin"><h2>KONO support</h2><p>Every KONO account and its study plans. Open one to add or fix things for someone in the normal KONO screens. A backup of their plan is kept first, and everything you view or change is logged where they can see it.</p>
  <div className="account-actions"><button className="primary" disabled={busy} onClick={()=>void load()}>{busy?'Loading…':accounts?'Refresh':'Show all accounts'}</button></div>
  {error&&<p role="alert">{error}</p>}
  {accounts&&<><label className="support-search">Find an account<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Email, name or plan"/></label><p className="wb-muted">{shown.length} of {accounts.length} accounts</p>
   <ul className="support-accounts">{shown.map(a=><li key={a.userId} className="support-account"><div><strong>{a.email||'(no email)'}</strong>{a.username&&<small> @{a.username}</small>}<p>{a.profiles||'No saved plan yet'}</p><small>Last saved {when(a.updatedAt)} · Last sign-in {when(a.lastSignInAt)} · Joined {when(a.createdAt)}</small></div>{a.userId===store.user?.id?<small>You</small>:<button type="button" disabled={!a.revision} onClick={()=>open(a)}>Open to help</button>}</li>)}</ul></>}
  {activity.length>0&&<details><summary>Recent support activity</summary><ul>{activity.map(item=><li key={item.id}>{new Date(item.createdAt).toLocaleString()} · {emailOf(item.adminId)} {item.action==='edit'?'changed':'opened'} {emailOf(item.accountId)}’s plan</li>)}</ul></details>}
  <details><summary>Add another support person</summary><p>Only the database owner can, in the Supabase SQL editor:</p><pre><code>{"insert into public.kono_admins(user_id)\nselect id from auth.users where email = 'their@email.com';"}</code></pre></details>
 </section>
}
