import { useState, type FormEvent } from 'react'
import type { AdminAccount, ClientError, Feedback, SupportActivity } from '../store/supabaseRemote'
import { LegalLink } from './Legal'
import type { usePlannerRepository } from '../store/repository'
import type { AppData } from '../store/model'
import { SaveStatus } from './AccountPanel'

/** The Settings-only account panels (account & data, backups, KONO support, feedback). They load when
 * Settings opens, so they aren't part of the startup download. */
type Store=ReturnType<typeof usePlannerRepository>
export function AccountPanel({store}:{store:Store}){
 const {repository}=store
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[signInSent,setSignInSent]=useState(false)
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Could not finish. Your working copy is preserved.')}finally{setBusy(false)}}
 return <section className="card account-panel" id="account-data"><span className="eyebrow">Account & data</span><h2>Your work, safely kept</h2><p>{store.user?'Your signed-in account owns these plans. Each device keeps a recovery cache.':'Local plans stay in this browser. Sign in to keep your own plans across devices.'}</p><SaveStatus store={store}/>{!store.user&&(repository.signInProvider==='email'?<form className="email-sign-in" onSubmit={e=>{e.preventDefault();void action(async()=>{await repository.signInWithEmail(email);setSignInSent(true)})}}><label>Email address<input required type="email" autoComplete="email" maxLength={320} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="primary" disabled={busy}>{busy?'Sending…':'Email me a sign-in link'}</button>{signInSent&&<p role="status">Check your email and open the KONO sign-in link on this device.</p>}</form>:<a className="primary button-link" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>)}<div className="account-actions"><button onClick={repository.retry} disabled={busy}>Retry saving</button>{store.user&&<button disabled={busy} onClick={()=>{if(window.confirm('Sign out and clear this account’s cached plan from this browser? Unsynced work must be saved first.'))void action(repository.signOut)}}>Sign out</button>}</div>
 {store.needsMigration&&<div className="recovery-notice"><h3>Bring this device’s plan to your account?</h3><p>Nothing is uploaded until you choose. Import only if these plans belong to you.</p><button onClick={()=>{if(window.confirm('These local plans belong to me. Copy them to my signed-in account?'))repository.importLegacy()}}>Import my local plans</button><button onClick={repository.skipMigration}>Start a separate account plan</button></div>}
 {store.recovery.map(file=><div className="recovery-notice" key={file.name}><p>{file.reason}</p><button onClick={()=>repository.downloadRecovery(file)}>Download original recovery file</button></div>)}
 {!!store.conflicts.length&&<div className="recovery-notice"><h3>Two copies need your attention</h3><p>No conflicting edits have been overwritten. Export your working copy, then choose the saved cloud copy. You can reapply your changes afterward.</p><button onClick={repository.export}>Export this working copy</button><button disabled={busy} onClick={()=>{if(window.confirm('Replace the working copy with the cloud version? Export first to keep your changes.'))void action(repository.useCloud)}}>Use cloud copy</button></div>}
 {store.user&&<details className="danger-zone"><summary>Delete cloud study data</summary><p>Deletes your KONO plans and cloud revision history. This does not delete your sign-in account. Export a backup first.</p><button disabled={busy} onClick={()=>{if(window.prompt('Type DELETE to erase your cloud study data and this account’s local cache.')==='DELETE')void action(repository.deleteAccountData)}}>Delete cloud study data</button></details>}
 
 <p><strong>One account per person.</strong> Study profiles organize your own terms or plans; they are not separate private logins. Sign out before another person uses a shared device. Local-only mode is shared by people using the same browser profile and does not sync to another phone.</p><details><summary>Privacy & storage</summary><p>KONO stores study plans, notes, settings and Sanctuary progress. Signed-in data is kept in this site’s database and a browser recovery cache; local mode stays on this device. Export a backup before clearing browser data. Interface fonts are requested from Google Fonts. Only enable live weather if you want your entered location sent to Open-Meteo. Music starts only when you press play. No advertising or analytics tracker is included.</p><p>Signed-in plans are backed up automatically each time you open KONO (the 30 most recent copies are kept). KONO support can open a signed-in account’s plan to help fix a problem. Every time that happens it is logged, and you can see it under Settings › Import & export › Backups › Support activity. Deleting your cloud study data also deletes its backups.</p><p>Sign out on shared computers. A downloaded backup contains your study information: keep it somewhere private.</p><p><LegalLink label="Read the full Terms & Privacy"/></p></details>{error&&<p role="alert">{error}</p>}</section>
}
/** Export a backup, review and restore one, and download recovery snapshots. */
export function BackupPanel({store}:{store:Store}){
 const {repository}=store
 const [candidate,setCandidate]=useState<AppData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [history,setHistory]=useState<{revision:number;created_at:string;bySupport?:boolean}[]>([])
 const [autoBackups,setAutoBackups]=useState<{revision:number;created_at:string;reason:'open'|'before-support'}[]|null>(null),[activity,setActivity]=useState<SupportActivity[]|null>(null)
 const cloud=!!store.user&&!store.support
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Could not finish. Your working copy is preserved.')}finally{setBusy(false)}}
 return <section className="card account-panel"><h3>Backups</h3><p>Download everything in one file, or restore from one. A backup contains your study information: keep it somewhere private.</p><div className="account-actions"><button onClick={repository.export}>Export backup</button><label className="button-link">Import backup<input type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>8_000_000){setError('Backup is too large. The limit is 8 MB.');return}void file.text().then(raw=>{try{setCandidate(repository.importPreview(raw));setError('')}catch(error){setError(error instanceof Error?error.message:'Invalid backup')}})}}/></label></div>{error&&<p role="alert">{error}</p>}
 {candidate&&<div className="recovery-notice"><h3>Review backup before replacing</h3><p>{candidate.profiles.length} plans · {candidate.tasks.length} assignments · {candidate.notes.length} notes · {candidate.exams.length} exams</p><p>This replaces the plans currently open here. Export your current work first.</p><button onClick={()=>{if(window.confirm('Replace the current plans with this backup?')){repository.replace(candidate);setCandidate(null)}}}>Use this backup</button><button onClick={()=>setCandidate(null)}>Cancel</button></div>}
 {repository.deviceCopy()&&!store.needsMigration&&<p className="recovery-notice">This browser also has a plan that was saved here before you signed in. <button type="button" onClick={()=>{const copy=repository.deviceCopy();if(copy)repository.downloadBackup(copy)}}>Download that plan</button> Then use Import backup to review it and bring it into your account.</p>}
 <details><summary>Recovery snapshots</summary><p>The five most recent device copies and up to twenty cloud revisions are retained. Download a snapshot, then use Import backup to review it before restoring.</p>{repository.localBackups().map((data,i)=><button key={i} onClick={()=>repository.downloadBackup(data)}>Download device copy {i+1}</button>)}{cloud&&<><button disabled={busy} onClick={()=>void action(async()=>{setHistory(await repository.cloudHistory())})}>Show cloud history</button><ul>{history.map(item=><li key={item.revision}><button disabled={busy} onClick={()=>void action(()=>repository.downloadCloudBackup(item.revision))}>Download revision {item.revision}</button> · {new Date(item.created_at).toLocaleString()}{item.bySupport&&' · changed by KONO support'}</li>)}</ul></>}</details>
 {cloud&&<details><summary>Automatic backups</summary><p>Each time you open KONO, a copy of your saved plan is kept (skipped when nothing changed). The 30 most recent are kept. Download one, then use Import backup to review it before restoring.</p><button disabled={busy} onClick={()=>void action(async()=>{setAutoBackups(await repository.autoBackups())})}>Show automatic backups</button>{autoBackups&&(autoBackups.length?<ul>{autoBackups.map(item=><li key={item.revision}><button disabled={busy} onClick={()=>void action(()=>repository.downloadAutoBackup(item.revision))}>Download</button> {new Date(item.created_at).toLocaleString()} · {item.reason==='before-support'?'kept before KONO support helped':'when you opened KONO'}</li>)}</ul>:<p>No automatic backups yet. One is kept the next time you open KONO after saving.</p>)}</details>}
 {cloud&&<details><summary>Nightly backup</summary><p>Every evening KONO saves one copy of your plan, replacing the previous night's. Download it, then use Import backup to review it before restoring.</p><button disabled={busy} onClick={()=>void action(async()=>{if(!await repository.downloadNightly())throw new Error('No nightly backup yet. The first one is made tonight.')})}>Download last night's backup</button></details>}
 {cloud&&<details><summary>Support activity</summary><p>KONO support can open your plan to help fix a problem. Every view and change is listed here.</p><button disabled={busy} onClick={()=>void action(async()=>{setActivity(await repository.supportActivity())})}>Show support activity</button>{activity&&(activity.length?<ul>{activity.map(item=><li key={item.id}>{new Date(item.createdAt).toLocaleString()} · KONO support {item.action==='edit'?'changed your plan':'opened your plan'}</li>)}</ul>:<p>KONO support has never opened your plan.</p>)}</details>}</section>
}

const when=(value:string|null)=>value?new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'never'
/** KONO support: every account, and a way to open one to help. The server re-checks support access on every call. */
export function SupportAdminPanel({store}:{store:Store}){
 const {repository}=store
 const [accounts,setAccounts]=useState<AdminAccount[]|null>(null),[activity,setActivity]=useState<SupportActivity[]>([]),[errors,setErrors]=useState<ClientError[]>([]),[feedback,setFeedback]=useState<Feedback[]>([]),[note,setNote]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{setBusy(true);setError('');try{const [list,log,errs,notes]=await Promise.all([repository.adminAccounts(),repository.adminActivity(),repository.adminErrors().catch(()=>[] as ClientError[]),repository.adminFeedback().catch(()=>[] as Feedback[])]);setAccounts(list);setActivity(log);setErrors(errs);setFeedback(notes)}catch(e){setError(e instanceof Error?e.message:'Could not load accounts.')}finally{setBusy(false)}}
 const emailOf=(id:string|null)=>id?accounts?.find(a=>a.userId===id)?.email??'an account':'a removed account'
 const needle=query.trim().toLowerCase()
 const shown=(accounts??[]).filter(a=>!needle||[a.email,a.profiles,a.username??''].some(v=>v.toLowerCase().includes(needle)))
 const nightly=async(account:AdminAccount)=>{setError('');setNote('');try{const at=await repository.adminDownloadNightly(account.userId);setNote(at?`Downloaded ${account.email}’s backup from ${new Date(at).toLocaleString()}.`:`${account.email} has no nightly backup yet.`)}catch(e){setError(e instanceof Error?e.message:'Could not download that backup.')}}
 const open=(account:AdminAccount)=>{if(!window.confirm(account.revision?`Open ${account.email}’s plan to help?\n\nA backup is kept first. What you view and change is logged, and they can see it.`:`Set up a plan for ${account.email}?\n\nThey haven’t saved anything yet. What you set up is logged, and they’ll see it when they sign in.`))return;try{repository.startSupport({id:account.userId,email:account.email})}catch(e){setError(e instanceof Error?e.message:'Could not open that account.')}}
 return <section className="card account-panel support-admin"><h2>KONO support</h2><p>Every KONO account and its study plans. Open one to add or fix things for someone in the normal KONO screens. A backup of their plan is kept first, and everything you view or change is logged where they can see it.</p>
  <div className="account-actions"><button className="primary" disabled={busy} onClick={()=>void load()}>{busy?'Loading…':accounts?'Refresh':'Show all accounts'}</button></div>
  {error&&<p role="alert">{error}</p>}{note&&<p role="status">{note}</p>}
  {accounts&&<><label className="support-search">Find an account<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Email, name or plan"/></label><p className="wb-muted">{shown.length} of {accounts.length} accounts</p>
   <ul className="support-accounts">{shown.map(a=><li key={a.userId} className="support-account"><div><strong>{a.email||'(no email)'}</strong>{a.username&&<small> @{a.username}</small>}<p>{a.profiles||'No saved plan yet'}</p><small>Last saved {when(a.updatedAt)} · Last sign-in {when(a.lastSignInAt)} · Joined {when(a.createdAt)}</small></div>{a.userId===store.user?.id?<small>You</small>:<span className="support-account-actions">{Boolean(a.revision)&&<button type="button" onClick={()=>void nightly(a)}>Nightly backup</button>}<button type="button" className={a.revision?undefined:'primary'} onClick={()=>open(a)}>{a.revision?'Open to help':'Set up their plan'}</button></span>}</li>)}</ul></>}
  {activity.length>0&&<details><summary>Recent support activity</summary><ul>{activity.map(item=><li key={item.id}>{new Date(item.createdAt).toLocaleString()} · {emailOf(item.adminId)} {item.action==='edit'?'changed':'opened'} {emailOf(item.accountId)}’s plan</li>)}</ul></details>}
  <PushKeysHelper/>
  {accounts&&<details open={feedback.length>0}><summary>Feedback{feedback.length?` · ${feedback.length}`:''}</summary>{feedback.length?<ul className="support-errors">{feedback.map(item=><li key={item.id}><p className="support-feedback-text">{item.message}</p><small>{new Date(item.createdAt).toLocaleString()} · {emailOf(item.userId)}{item.page?' · on '+item.page:''}{item.appVersion?' · '+item.appVersion:''}</small><button type="button" onClick={()=>void repository.adminDeleteFeedback(item.id).then(()=>setFeedback(f=>f.filter(x=>x.id!==item.id))).catch(e=>setError(e instanceof Error?e.message:'Could not remove it.'))}>Done — remove</button></li>)}</ul>:<p>No feedback yet.</p>}</details>}
  {accounts&&<details><summary>App errors{errors.length?` · ${errors.length}`:''}</summary>{errors.length?<ul className="support-errors">{errors.map(item=><li key={item.id}><strong>{item.message}</strong><small>{new Date(item.createdAt).toLocaleString()} · {emailOf(item.userId)}{item.page?' · '+item.page:''}{item.appVersion?' · '+item.appVersion:''}</small>{item.detail&&<details><summary>Details</summary><pre>{item.detail}</pre></details>}</li>)}</ul>:<p>No app errors reported in the last 30 days.</p>}</details>}
  <details><summary>Add another support person</summary><p>Only the database owner can, in the Supabase SQL editor:</p><pre><code>{"insert into public.kono_admins(user_id)\nselect id from auth.users where email = 'their@email.com';"}</code></pre></details>
 </section>
}

/** "Send feedback": a short note to KONO support, with the page it was sent from. */
export function FeedbackButton({store}:{store:Store}){
 const [open,setOpen]=useState(false),[text,setText]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState('')
 const send=async(e:FormEvent)=>{e.preventDefault();if(!text.trim()||busy)return;setBusy(true);setError('');try{await store.repository.sendFeedback(text);setText('');setStatus('Thank you! KONO support will read it.')}catch(err){setError(err instanceof Error?err.message:'Could not send it. Try again in a moment.')}finally{setBusy(false)}}
 return <div className="feedback-box">{!open?<button type="button" onClick={()=>{setOpen(true);setStatus('')}}>💬 Send feedback</button>:<form onSubmit={send}><label>What’s working, what’s confusing, or what’s broken?<textarea autoFocus rows={4} maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder="For example: the class upload didn’t find my Friday lab."/></label>{!store.user&&<p className="wb-muted">Sign in with your email (Settings › Plans &amp; account) to send feedback.</p>}<p className="wb-muted">Sent with the page you’re on and your app version, so support can find the problem. Don’t include passwords.</p><div className="wb-toolbar"><button className="primary" disabled={busy||!text.trim()||!store.user}>{busy?'Sending…':'Send'}</button><button type="button" onClick={()=>{setOpen(false);setError('')}}>Close</button></div></form>}{status&&<p role="status">{status}</p>}{error&&<p role="alert">{error}</p>}</div>
}

const b64url=(bytes:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')
/** One-time setup for lock-screen reminders: makes the key pair Vercel needs (VAPID), right in this
 * browser. Nothing is sent or saved; copy the two values into Vercel's Environment Variables. */
function PushKeysHelper(){
 const [keys,setKeys]=useState<{publicKey:string;privateKey:string}|null>(null),[error,setError]=useState('')
 const make=async()=>{try{const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const raw=await crypto.subtle.exportKey('raw',pair.publicKey),jwk=await crypto.subtle.exportKey('jwk',pair.privateKey);setKeys({publicKey:b64url(raw),privateKey:jwk.d??''})}catch{setError('This browser couldn’t make keys. Try Chrome or Safari.')}}
 return <details className="push-keys"><summary>Lock-screen reminder keys (one-time setup)</summary><p>Lock-screen reminders need a key pair. Make it here once, then add both values in Vercel › Project › Settings › Environment Variables and redeploy. The private key isn’t saved anywhere else. If you make a new pair later, everyone has to turn reminders on again.</p>{!keys?<button type="button" onClick={()=>void make()}>Create reminder keys</button>:<dl><dt>VAPID_PUBLIC_KEY</dt><dd><code>{keys.publicKey}</code></dd><dt>VAPID_PRIVATE_KEY</dt><dd><code>{keys.privateKey}</code></dd></dl>}{error&&<p role="alert">{error}</p>}</details>
}
