import { useState, type FormEvent } from 'react'
import type { usePlannerRepository } from '../store/repository'
import { type AppData, localDate } from '../store/model'
import {APP_VERSION} from '../version'
type Store=ReturnType<typeof usePlannerRepository>
export function SaveStatus({store}:{store:Store}){
 return <div className="save-status"><small>Build {APP_VERSION.split('production-')[1]}</small> · <span role="status">{store.user?'Account: '+store.user.email:'This device only'} · {store.status}</span>{store.error&&<p role="alert">{store.error} <button onClick={store.repository.export}>Export working copy</button> <button onClick={store.repository.retry}>Retry</button></p>}</div>
}
export function AccountPanel({store}:{store:Store}){
 const {repository}=store
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[signInSent,setSignInSent]=useState(false)
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Could not finish. Your working copy is preserved.')}finally{setBusy(false)}}
 return <section className="card account-panel" id="account-data"><span className="eyebrow">Account & data</span><h2>Your work, safely kept</h2><p>{store.user?'Your signed-in account owns these plans. Each device keeps a recovery cache.':'Local plans stay in this browser. Sign in to keep your own plans across devices.'}</p><SaveStatus store={store}/>{!store.user&&(repository.signInProvider==='email'?<form className="email-sign-in" onSubmit={e=>{e.preventDefault();void action(async()=>{await repository.signInWithEmail(email);setSignInSent(true)})}}><label>Email address<input required type="email" autoComplete="email" maxLength={320} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="primary" disabled={busy}>{busy?'Sending…':'Email me a sign-in link'}</button>{signInSent&&<p role="status">Check your email and open the KONO sign-in link on this device.</p>}</form>:<a className="primary button-link" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>)}<div className="account-actions"><button onClick={repository.retry} disabled={busy}>Retry saving</button>{store.user&&<button disabled={busy} onClick={()=>{if(window.confirm('Sign out and clear this account’s cached plan from this browser? Unsynced work must be saved first.'))void action(repository.signOut)}}>Sign out</button>}</div>
 {store.needsMigration&&<div className="recovery-notice"><h3>Bring this device’s plan to your account?</h3><p>Nothing is uploaded until you choose. Import only if these plans belong to you.</p><button onClick={()=>{if(window.confirm('These local plans belong to me. Copy them to my signed-in account?'))repository.importLegacy()}}>Import my local plans</button><button onClick={repository.skipMigration}>Start a separate account plan</button></div>}
 {store.recovery.map(file=><div className="recovery-notice" key={file.name}><p>{file.reason}</p><button onClick={()=>repository.downloadRecovery(file)}>Download original recovery file</button></div>)}
 {!!store.conflicts.length&&<div className="recovery-notice"><h3>Two copies need your attention</h3><p>No conflicting edits have been overwritten. Export your working copy, then choose the saved cloud copy. You can reapply your changes afterward.</p><button onClick={repository.export}>Export this working copy</button><button disabled={busy} onClick={()=>{if(window.confirm('Replace the working copy with the cloud version? Export first to keep your changes.'))void action(repository.useCloud)}}>Use cloud copy</button></div>}
 {store.user&&<details className="danger-zone"><summary>Delete cloud study data</summary><p>Deletes your KONO plans and cloud revision history. This does not delete your sign-in account. Export a backup first.</p><button disabled={busy} onClick={()=>{if(window.prompt('Type DELETE to erase your cloud study data and this account’s local cache.')==='DELETE')void action(repository.deleteAccountData)}}>Delete cloud study data</button></details>}
 
 <p><strong>One account per person.</strong> Study profiles organize your own terms or plans; they are not separate private logins. Sign out before another person uses a shared device. Local-only mode is shared by people using the same browser profile and does not sync to another phone.</p><details><summary>Privacy & storage</summary><p>KONO stores study plans, notes, settings and Sanctuary progress. Signed-in data is kept in this site’s database and a browser recovery cache; local mode stays on this device. Export a backup before clearing browser data. Interface fonts are requested from Google Fonts. Only enable live weather if you want your entered location sent to Open-Meteo. Music starts only when you press play. No advertising or analytics tracker is included.</p><p>Sign out on shared computers. A downloaded backup contains your study information: keep it somewhere private.</p></details>{error&&<p role="alert">{error}</p>}</section>
}
/** Export a backup, review and restore one, and download recovery snapshots. */
export function BackupPanel({store}:{store:Store}){
 const {repository}=store
 const [candidate,setCandidate]=useState<AppData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [history,setHistory]=useState<{revision:number;created_at:string}[]>([])
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Could not finish. Your working copy is preserved.')}finally{setBusy(false)}}
 return <section className="card account-panel"><h3>Backups</h3><p>Download everything in one file, or restore from one. A backup contains your study information: keep it somewhere private.</p><div className="account-actions"><button onClick={repository.export}>Export backup</button><label className="button-link">Import backup<input type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>8_000_000){setError('Backup is too large. The limit is 8 MB.');return}void file.text().then(raw=>{try{setCandidate(repository.importPreview(raw));setError('')}catch(error){setError(error instanceof Error?error.message:'Invalid backup')}})}}/></label></div>{error&&<p role="alert">{error}</p>}
 {candidate&&<div className="recovery-notice"><h3>Review backup before replacing</h3><p>{candidate.profiles.length} plans · {candidate.tasks.length} assignments · {candidate.notes.length} notes · {candidate.exams.length} exams</p><p>This replaces the plans currently open here. Export your current work first.</p><button onClick={()=>{if(window.confirm('Replace the current plans with this backup?')){repository.replace(candidate);setCandidate(null)}}}>Use this backup</button><button onClick={()=>setCandidate(null)}>Cancel</button></div>}
 <details><summary>Recovery snapshots</summary><p>The five most recent device copies and up to twenty cloud revisions are retained. Download a snapshot, then use Import backup to review it before restoring.</p>{repository.localBackups().map((data,i)=><button key={i} onClick={()=>repository.downloadBackup(data)}>Download device copy {i+1}</button>)}{store.user&&<><button disabled={busy} onClick={()=>void action(async()=>{setHistory(await repository.cloudHistory())})}>Show cloud history</button><ul>{history.map(item=><li key={item.revision}><button disabled={busy} onClick={()=>void action(()=>repository.downloadCloudBackup(item.revision))}>Download revision {item.revision}</button> · {new Date(item.created_at).toLocaleString()}</li>)}</ul></>}</details></section>
}
/** Shown instead of the welcome screen when saved data exists but this build couldn't read it. */
export function RecoveryScreen({store}:{store:Store}){
 const [status,setStatus]=useState('')
 const download=async()=>{setStatus('');try{setStatus(await store.repository.downloadUnreadable()?'Downloaded. Keep that file somewhere safe.':'')}catch{setStatus('Could not prepare the download. Your data is still in this browser.')}}
 return <main className="onboarding page-stack"><section className="card recovery-screen" role="alert"><span className="eyebrow">KONO</span><h1>We couldn't open your saved plan</h1>
  <p><strong>Your data is safe.</strong> Nothing has been changed or deleted, and KONO won't save over it while this screen is showing.</p>
  <p>This can happen right after an update. Trying again often fixes it. If it doesn't, download a copy so nothing can be lost, then check back after the next update.</p>
  <div className="account-actions"><button className="primary" onClick={()=>window.location.reload()}>Try again</button><button onClick={()=>void download()}>Download a copy of my data</button>{store.recovery.filter(file=>file.raw).map(file=><button key={file.name} onClick={()=>store.repository.downloadRecovery(file)}>Download older copy ({file.name})</button>)}</div>
  {status&&<p role="status">{status}</p>}
  {store.error&&<details><summary>Technical details</summary><p>{store.error}</p></details>}
 </section></main>
}
export function Onboarding({store}:{store:Store}){
 const profile=store.data.profiles[0], [name,setName]=useState(''),[label,setLabel]=useState('My study plan')
 const submit=(e:FormEvent)=>{e.preventDefault();if(!name.trim()||!label.trim())return;store.repository.update(d=>({...d,onboardingComplete:true,profiles:d.profiles.map(p=>p.id===profile.id?{...p,name:name.trim(),label:label.trim()}:p)}))}
 return <main className="onboarding page-stack"><form className="card" onSubmit={submit}><span className="eyebrow">Welcome to KONO</span><h1>A little space for steady progress.</h1><p>Start with your own plan. Add subjects, small assignments and notes; your Sanctuary grows as you finish work.</p><label>Your name<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)} autoComplete="given-name"/></label><label>Plan name<input required maxLength={200} value={label} onChange={e=>setLabel(e.target.value)}/></label><button className="primary" disabled={store.needsMigration}>Create my study plan</button><button type="button" disabled={store.needsMigration} onClick={()=>void store.repository.update(d=>({...d,onboardingComplete:true,notes:[...d.notes,{id:'demo-note-'+profile.id,profileId:profile.id,subjectId:'',title:'Welcome to your board',body:'Edit this note, change its color, or move it to Trash. Your own work starts here.',created:new Date().toISOString(),pinned:true}],tasks:[...d.tasks,{id:'demo-task-'+profile.id,profileId:profile.id,subjectId:'',title:'Try completing an assignment',due:localDate(),done:false,notes:'This optional demo task can be edited, reopened, or removed.'}]}))}>Try a small demo instead</button></form><AccountPanel store={store}/></main>
}
