import {useState,type CSSProperties} from 'react'
import {useDraftState} from '../hooks/useDraftState'
import {uid,type AppData} from '../store/model'
import {classTime,nextClassDate,saveClassNote,updateClass,type ClassOccurrence} from '../store/classSchedule'
import type {PlannerRepository} from '../store/repository'
export default function ClassOccurrenceCard({item,save,draftKey,onAssignment,compact=false,subjectColor='#c987a2'}:{item:ClassOccurrence;save:PlannerRepository['update'];draftKey:string;onAssignment?:()=>void;compact?:boolean;subjectColor?:string}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [text,setText]=useDraftState(draftKey+':'+item.id+':note',item.block.occurrenceNotes?.[item.date]??'')
 const [reminder,setReminder]=useDraftState(draftKey+':'+item.id+':reminder','')
 const [remindDate,setRemindDate]=useDraftState(draftKey+':'+item.id+':remindDate',nextClassDate(item)??item.date)
 const done=item.block.completedDates?.includes(item.date),skipped=item.block.skippedDates?.includes(item.date)
 const run=async(action:(d:AppData)=>AppData,success:string)=>{if(busy)return;setBusy(true);try{if(await save(action))setMessage(success);else setMessage('Not saved yet. Your draft is kept here.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save.')}finally{setBusy(false)}}
 const startTime=classTime(item.displayStart??item.block.start),endTime=classTime(item.displayEnd??item.block.end)
 const time=item.timePending?'Times not confirmed':startTime+'–'+endTime
 const complete=()=>void run(d=>updateClass(d,item,b=>({...b,completedDates:b.completedDates?.includes(item.date)?b.completedDates.filter(v=>v!==item.date):[...(b.completedDates??[]),item.date]})),'Class status saved.')
 const skip=()=>void run(d=>updateClass(d,item,b=>({...b,skippedDates:b.skippedDates?.includes(item.date)?b.skippedDates.filter(v=>v!==item.date):[...(b.skippedDates??[]),item.date]})),'Only this date changed.')
 return <article className={'wb-record wb-class'+(compact?' wb-class-compact':'')+(done?' is-complete':'')} style={{'--class-accent':subjectColor} as CSSProperties}>
 {compact?<div className="wb-class-compact-row"><time>{time}</time><div className="wb-class-compact-copy"><h3>{item.block.label}</h3>{item.block.location&&<small>{item.block.location}</small>}{skipped&&<small>Skipped today</small>}</div><div className="wb-class-quick">{onAssignment&&<button className="primary" onClick={onAssignment}>＋ Assignment</button>}<button onClick={()=>setOpen(!open)}>{open?'Close':'＋ Note'}</button><details className="wb-class-more"><summary aria-label={'More actions for '+item.block.label}>•••</summary><div><button disabled={busy} onClick={complete}>{done?'Reopen':'Complete'}</button><button disabled={busy} onClick={skip}>{skipped?'Restore today':'Skip today'}</button></div></details></div></div>:<><small>{item.season.school?item.day:'Recurring class / activity'} · {item.date}</small><h3>{item.block.label}</h3><p><strong>{time}</strong>{item.block.location?' · '+item.block.location:''}{skipped?' · Skipped this date':''}</p></>}
 {item.block.occurrenceNotes?.[item.date]&&<p className="wb-class-note">{item.block.occurrenceNotes[item.date]}</p>}
 {!compact&&<div className="wb-toolbar">{onAssignment&&<button className="primary" onClick={onAssignment}>＋ Assignment for this class</button>}<button onClick={()=>setOpen(!open)}>{open?'Close notes':'Note / reminder'}</button><button disabled={busy} onClick={complete}>{done?'Reopen':'Complete'}</button><button disabled={busy} onClick={skip}>{skipped?'Restore this date':'Skip this date'}</button></div>}
 {open&&<div className="wb-class-editor"><label>Note for {item.date} only<textarea maxLength={10000} value={text} onChange={e=>setText(e.target.value)} placeholder="What happened in this class? What should I bring next time?"/></label><button disabled={busy} onClick={()=>void run(d=>saveClassNote(d,item,text),'Note saved for this date only.')}>Save class note</button><hr/><label>Reminder title<input maxLength={1000} value={reminder} onChange={e=>setReminder(e.target.value)} placeholder="Bring Biology book"/></label><label>Remind me on<input type="date" value={remindDate} onInput={e=>setRemindDate(e.currentTarget.value)}/></label><div className="wb-toolbar">{nextClassDate(item)&&<button onClick={()=>setRemindDate(nextClassDate(item)!)}>Next class · {nextClassDate(item)}</button>}<button disabled={busy||!reminder.trim()||!remindDate} onClick={()=>{const id=uid('reminder');void run(d=>{if(d.activeProfileId!==item.season.profileId)throw Error('Your profile changed.');return {...d,calendarEvents:[...d.calendarEvents,{id,profileId:item.season.profileId,subjectId:item.block.subjectId??'',title:reminder.trim(),date:remindDate,kind:'personal',done:false,notes:'Reminder from '+item.block.label+' on '+item.date+'. '+classTime(item.block.start)+'–'+classTime(item.block.end)}]}},'Reminder added to the calendar and daily agenda.')}}>Add reminder</button></div><p className="wb-muted">Shown inside KONO on the selected day, or as overdue until completed. No phone notification is sent while KONO is closed.</p></div>}
 {message&&<p role="status">{message}</p>}
 </article>
}
