import {useState,type CSSProperties} from 'react'
import {useDraftState} from '../hooks/useDraftState'
import {uid,type AppData} from '../store/model'
import {classTime,nextClassDate,saveClassNote,updateClass,type ClassOccurrence} from '../store/classSchedule'
import type {PlannerRepository} from '../store/repository'
type DueItem={id:string;title:string;kind:'assignment'|'exam'|'note'|'reminder';countdown:string;collection:string;entry:unknown}
type AddKind='assignment'|'note'|'exam'|'reminder'
export default function ClassOccurrenceCard({item,save,draftKey,onAdd,onRemoveDue,dueItems=[],compact=false,subjectColor='#c987a2'}:{item:ClassOccurrence;save:PlannerRepository['update'];draftKey:string;onAdd?:(kind:AddKind)=>void;onRemoveDue?:(due:DueItem)=>void;dueItems?:DueItem[];compact?:boolean;subjectColor?:string}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [text,setText]=useDraftState(draftKey+':'+item.id+':note',item.block.occurrenceNotes?.[item.date]??'')
 const [reminder,setReminder]=useDraftState(draftKey+':'+item.id+':reminder','')
 const [remindDate,setRemindDate]=useDraftState(draftKey+':'+item.id+':remindDate',nextClassDate(item)??item.date)
 const done=item.block.completedDates?.includes(item.date),skipped=item.block.skippedDates?.includes(item.date)
 const run=async(action:(d:AppData)=>AppData,success:string)=>{if(busy)return;setBusy(true);try{if(await save(action))setMessage(success);else setMessage('Not saved yet. Your draft is kept here.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save.')}finally{setBusy(false)}}
 const startTime=classTime(item.displayStart??item.block.start),endTime=classTime(item.displayEnd??item.block.end)
 const time=item.timePending?'Times not confirmed':startTime+'–'+endTime
 const complete=()=>void run(d=>updateClass(d,item,b=>({...b,completedDates:b.completedDates?.includes(item.date)?b.completedDates.filter(v=>v!==item.date):[...(b.completedDates??[]),item.date]})),'Class status saved.')
 const skip=()=>void run(d=>updateClass(d,item,b=>({...b,skippedDates:b.skippedDates?.includes(item.date)?b.skippedDates.filter(v=>v!==item.date):[...(b.skippedDates??[]),item.date]})),'Only this date changed.')
 const addMenu=onAdd&&<details className="wb-class-add"><summary>＋ Add</summary><div><button onClick={()=>onAdd('assignment')}>Assignment</button><button onClick={()=>onAdd('note')}>Study note</button><button className="is-priority" onClick={()=>onAdd('exam')}>★ Exam / project</button><button onClick={()=>onAdd('reminder')}>Add reminder</button><button onClick={()=>setOpen(true)}>Open note editor</button></div></details>
 return <article className={'wb-record wb-class'+(compact?' wb-class-compact':'')+(done?' is-complete':'')} style={{'--class-accent':subjectColor} as CSSProperties}>
 {compact?<div className="wb-class-compact-row"><time>{time}</time><div className="wb-class-compact-copy"><h3>{item.block.label}</h3>{item.block.location&&<small>{item.block.location}</small>}{skipped&&<small>Skipped today</small>}</div><div className="wb-class-quick">{addMenu}<details className="wb-class-more"><summary aria-label={'More actions for '+item.block.label}>•••</summary><div><button disabled={busy} onClick={complete}>{done?'Reopen':'Complete'}</button><button disabled={busy} onClick={skip}>{skipped?'Restore today':'Skip today'}</button></div></details></div></div>:<><small>{item.season.school?item.day:'Recurring class / activity'} · {item.date}</small><h3>{item.block.label}</h3><p><strong>{time}</strong>{item.block.location?' · '+item.block.location:''}{skipped?' · Skipped this date':''}</p></>}
 {dueItems.length>0&&<div className="wb-class-due"><strong>For this class</strong>{dueItems.map(due=><span className={'wb-class-due-item kind-'+due.kind} key={due.id}><b>{due.kind==='exam'?'★':due.kind==='reminder'?'!':due.kind==='note'?'◆':'○'}</b><span>{due.title}</span><small>{due.countdown}</small>{onRemoveDue&&<button type="button" className="wb-class-due-remove" aria-label={'Remove '+due.title} onClick={()=>onRemoveDue(due)}>✕</button>}</span>)}</div>}
 {item.block.occurrenceNotes?.[item.date]&&<p className="wb-class-note">{item.block.occurrenceNotes[item.date]}</p>}
 {!compact&&<div className="wb-toolbar">{addMenu}<button onClick={()=>setOpen(!open)}>{open?'Close notes':'Note / reminder'}</button><button disabled={busy} onClick={complete}>{done?'Reopen':'Complete'}</button><button disabled={busy} onClick={skip}>{skipped?'Restore this date':'Skip this date'}</button></div>}
 {open&&<div className="wb-class-editor"><label>Note for {item.date} only<textarea maxLength={10000} value={text} onChange={e=>setText(e.target.value)} placeholder="What happened in this class? What should I bring next time?"/></label><button disabled={busy||!text.trim()} onClick={()=>void run(d=>{const source='class-occurrence:'+item.id,note=d.notes.find(n=>n.profileId===item.season.profileId&&n.source===source),saved=saveClassNote(d,item,text),next={id:note?.id??uid('note'),profileId:item.season.profileId,subjectId:item.block.subjectId??'',title:item.block.label+' · '+item.date,body:text.trim(),created:note?.created??new Date().toISOString(),source,pinned:true,completed:false,color:note?.color??'#fff2b4',textColor:note?.textColor??'#2f2942',font:note?.font??'rounded',size:note?.size??'medium',position:note?.position??Math.max(0,...d.notes.filter(n=>n.profileId===item.season.profileId).map(n=>n.position??0))+1};return {...saved,notes:note?saved.notes.map(n=>n.id===note.id?{...n,...next}:n):[...saved.notes,next]}},'Class note saved and pinned to Study Notes.')}>Save & pin class note</button><hr/><label>Reminder title<input maxLength={1000} value={reminder} onChange={e=>setReminder(e.target.value)} placeholder="Bring Biology book"/></label><label>Remind me on<input type="date" value={remindDate} onInput={e=>setRemindDate(e.currentTarget.value)}/></label><div className="wb-toolbar">{nextClassDate(item)&&<button onClick={()=>setRemindDate(nextClassDate(item)!)}>Next class · {nextClassDate(item)}</button>}<button disabled={busy||!reminder.trim()||!remindDate} onClick={()=>{const id=uid('reminder');void run(d=>{if(d.activeProfileId!==item.season.profileId)throw Error('Your profile changed.');return {...d,calendarEvents:[...d.calendarEvents,{id,profileId:item.season.profileId,subjectId:item.block.subjectId??'',title:reminder.trim(),date:remindDate,kind:'personal',done:false,notes:'Reminder from '+item.block.label+' on '+item.date+'. '+classTime(item.block.start)+'–'+classTime(item.block.end)}]}},'Reminder added to the calendar and daily agenda.')}}>Add reminder</button></div><p className="wb-muted">The class note is pinned to Study Notes. Reminders appear inside KONO on the selected day. No phone notification is sent while KONO is closed.</p></div>}
 {message&&<p role="status">{message}</p>}
 </article>
}
