import { useEffect, useId, useRef, useState } from 'react'
type Command={label:string;hint:string;run:()=>void}
export default function CommandPalette({commands,onClose}:{commands:Command[];onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null)
 const [query,setQuery]=useState(''),[active,setActive]=useState(0)
 const id=useId(),matches=commands.filter(c=>(c.label+' '+c.hint).toLowerCase().includes(query.toLowerCase())).slice(0,10),index=Math.min(active,Math.max(0,matches.length-1))
 useEffect(()=>{const opener=document.activeElement as HTMLElement|null;dialog.current?.showModal();input.current?.focus();return()=>opener?.focus()},[])
 const run=(command?:Command)=>{if(command){command.run();onClose()}}
 return <dialog ref={dialog} className="command-palette command-dialog" aria-label="Search your work" onCancel={onClose}><div className="command-input"><span aria-hidden="true">⌕</span><input ref={input} role="combobox" aria-label="Search assignments, notes, exams, and pages" aria-expanded="true" aria-controls={id} aria-autocomplete="list" aria-activedescendant={matches.length?`${id}-${index}`:undefined} value={query} onChange={e=>{setQuery(e.target.value);setActive(0)}} onKeyDown={e=>{if(e.nativeEvent.isComposing)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setActive((index+(e.key==='ArrowDown'?1:-1)+matches.length)%Math.max(1,matches.length))}if(e.key==='Enter'){e.preventDefault();run(matches[index])}}} placeholder="Search your study plan…"/><button type="button" onClick={onClose} aria-label="Close search">×</button></div><div id={id} role="listbox" className="command-results" aria-label="Matching actions">{matches.map((c,i)=><div role="option" aria-selected={index===i} id={`${id}-${i}`} key={i} onMouseDown={e=>e.preventDefault()} onClick={()=>run(c)} className={index===i?'active':''}><strong>{c.label}</strong><small>{c.hint}</small></div>)}{!matches.length&&<p>No matching command.</p>}</div><footer>↑↓ Navigate · Enter Open · Escape Close</footer></dialog>
}
