import {useState,type FormEvent} from 'react'
import {TwelveHourTimeInput} from '../LegacyApp'
import {classTime} from '../store/classSchedule'
import {useDraftState} from '../hooks/useDraftState'
import {blankWeek,dayNames,localDate,uid,type AppData,type StudySeason,type ScheduleBlock} from '../store/model'
import type {PlannerRepository} from '../store/repository'
export default function SchedulePanel({data,save,draftKey}:{draftKey:string;data:AppData;save:PlannerRepository['update']}){
 const seasons=data.studySeasons.filter(s=>s.profileId===data.activeProfileId&&!s.school)
 const [selected,setSelected]=useDraftState(draftKey+':selected',seasons.find(s=>s.active)?.id??seasons[0]?.id??''),[day,setDay]=useDraftState<string>(draftKey+':day',dayNames[new Date().getDay()])
 const season=seasons.find(s=>s.id===selected)??seasons[0]
 const [draft,setDraft]=useDraftState<StudySeason|null>(draftKey+':season',null),[block,setBlock]=useDraftState<ScheduleBlock|null>(draftKey+':block',null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [base,setBase]=useDraftState<StudySeason|null>(draftKey+':base',null)
 const [removal,setRemoval]=useState<{message:string;run:()=>void}|null>(null)
 const begin=(s:StudySeason)=>{setDraft({...s});setBase(seasons.find(x=>x.id===s.id)??null);setBlock(null)}
 const store=async(e:FormEvent)=>{
  e.preventDefault();if(!draft||busy)return;setBusy(true);setError('')
  try{
   if(draft.end<draft.start)throw Error('End date must be on or after the start date.')
   if(block&&((block.dateStart??draft.start)<draft.start||(block.dateEnd??draft.end)>draft.end||(block.dateEnd??draft.end)<(block.dateStart??draft.start)))throw Error('Class dates must fall inside the season and end on or after they start.')
   if(block&&block.end<=block.start)throw Error('End time must be later than start time.')
   let next=draft
   if(block)next={...next,week:{...next.week,[day]:next.week[day].some(b=>b.id===block.id)?next.week[day].map(b=>b.id===block.id?block:b):[...next.week[day],block]}}
   const saved=await save(d=>{if(d.activeProfileId!==next.profileId)throw Error('Your profile changed.');const current=d.studySeasons.find(s=>s.id===next.id);if(JSON.stringify(current??null)!==JSON.stringify(base))throw Error('This schedule changed elsewhere. Reopen it before saving.');return {...d,studySeasons:current?d.studySeasons.map(s=>s.id===next.id?next:s):[...d.studySeasons,next]}})
   if(saved){setSelected(next.id);setDraft(null);setBlock(null)}else setError('Not saved yet. Your draft is still here.')
  }catch(e){setError(e instanceof Error?e.message:'Could not save.')}finally{setBusy(false)}
 }
 return <section className="wb-panel" id="weekly-schedules"><div className="wb-section-head"><h2>Weekly schedules & seasons</h2><button onClick={()=>begin({id:uid('season'),profileId:data.activeProfileId,name:'New schedule',start:localDate(),end:localDate(new Date(Date.now()+90*86400000)),active:!seasons.length,week:blankWeek()})}>＋ New season</button></div>
 <label>Season<select value={season?.id??''} onChange={e=>{setSelected(e.target.value);setDraft(null);setBlock(null)}}>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}{s.active?' · Active':''}</option>)}</select></label>
 {season&&<><p>{season.start} – {season.end}{season.end<localDate()?' · Ended':''}</p><div className="wb-toolbar"><button onClick={()=>begin(season)}>Edit dates / name</button><button onClick={()=>void save(d=>({...d,studySeasons:d.studySeasons.map(s=>s.profileId===data.activeProfileId&&s.id===season.id?{...s,active:!s.active}:s)}))}>{season.active?'Pause schedule':'Activate schedule'}</button><button onClick={()=>begin({...season,id:uid('season'),name:season.name+' (copy)',active:false,week:Object.fromEntries(Object.entries(season.week).map(([k,v])=>[k,v.map(b=>({...b,id:uid('block'),completedDates:[],skippedDates:[],occurrenceNotes:{}}))]))})}>Duplicate</button><button onClick={()=>{setRemoval({message:'Move this season and its weekly blocks to Trash?',run:()=>{void save(d=>({...d,studySeasons:d.studySeasons.filter(s=>s.id!==season.id)}))}})}}>Move season to Trash</button></div>
 <label>Weekday<select value={day} onChange={e=>{setDay(e.target.value);setDraft(null);setBlock(null)}}>{dayNames.map(d=><option key={d}>{d}</option>)}</select></label>
 {(season.week[day]??[]).map(b=><article className="wb-record" key={b.id}><h3>{b.label}</h3><p>{classTime(b.start)}–{classTime(b.end)} · {b.kind}<br/>{b.dateStart??season.start} – {b.dateEnd??season.end}</p><div className="wb-toolbar"><button onClick={()=>{begin(season);setBlock({...b})}}>Edit block</button><button onClick={()=>{begin(season);setBlock({...b,id:uid('block'),label:b.label+' (copy)',completedDates:[],skippedDates:[],occurrenceNotes:{}})}}>Duplicate</button><button onClick={()=>{setRemoval({message:'Remove this recurring block from every '+day+'? You can restore it from Trash.',run:()=>{void save(d=>({...d,studySeasons:d.studySeasons.map(s=>s.id===season.id?{...s,week:{...s.week,[day]:s.week[day].filter(x=>x.id!==b.id)}}:s)}))}})}}>Move block to Trash</button></div></article>)}
 <button onClick={()=>{begin(season);setBlock({id:uid('block'),label:'',start:'16:00',end:'17:00',kind:'study',dateStart:season.start,dateEnd:season.end})}}>＋ Add recurring class / activity</button></>}
 {removal&&<div className="wb-record" role="group" aria-label="Confirm schedule removal"><p>{removal.message}</p><button onClick={()=>{removal.run();setRemoval(null)}}>Confirm removal</button><button onClick={()=>setRemoval(null)}>Keep schedule</button></div>}
 {draft&&<form className="wb-record" onSubmit={store}><fieldset disabled={busy}><h3>{block?'Recurring class / activity':'Edit season'}</h3>{block?<><p>Repeats every {day} during the dates below. Notes are written on individual dates in the calendar.</p><label>Class / activity<input autoFocus required maxLength={1000} value={block.label} onChange={e=>setBlock({...block,label:e.target.value})}/></label><div className="wb-form-grid"><div><label>Start time</label><TwelveHourTimeInput label="Class start" value={block.start} onChange={start=>setBlock({...block,start})}/></div><div><label>End time</label><TwelveHourTimeInput label="Class end" value={block.end} onChange={end=>setBlock({...block,end})}/></div></div><div className="wb-form-grid"><label>First date<input required type="date" min={draft.start} max={draft.end} value={block.dateStart??draft.start} onInput={e=>setBlock({...block,dateStart:e.currentTarget.value})}/></label><label>Last date<input required type="date" min={block.dateStart??draft.start} max={draft.end} value={block.dateEnd??draft.end} onInput={e=>setBlock({...block,dateEnd:e.currentTarget.value})}/></label></div><label>Subject<select value={block.subjectId??''} onChange={e=>setBlock({...block,subjectId:e.target.value})}><option value="">General / unassigned</option>{data.subjects.filter(s=>s.profileId===data.activeProfileId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Room / location<input maxLength={200} value={block.location??''} onChange={e=>setBlock({...block,location:e.target.value})}/></label><label>Kind<select value={block.kind} onChange={e=>setBlock({...block,kind:e.target.value as ScheduleBlock['kind']})}>{['study','routine','break','hobby'].map(k=><option key={k}>{k}</option>)}</select></label></>:<><label>Season name<input required maxLength={200} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Starts<input required type="date" value={draft.start} onInput={e=>setDraft({...draft,start:e.currentTarget.value})}/></label><label>Ends<input required type="date" value={draft.end} onInput={e=>setDraft({...draft,end:e.currentTarget.value})}/></label></>}
 {error&&<p role="alert">{error}</p>}<div className="wb-toolbar"><button className="primary">Save schedule</button><button type="button" onClick={()=>{setDraft(null);setBlock(null)}}>Cancel</button></div></fieldset></form>}
 </section>
}
