import {useEffect,useRef,useState} from 'react'
import {type StudySeason} from '../store/model'
import {addTimetableRows,parseNdaSixDaySchedule,parseWeeklyCollegeSchedule,suggestRotatingClasses,type RotatingImportRow} from '../store/schoolImport'
export default function SchoolTimetableImport({season,change,onReview}:{season:StudySeason;change:(s:StudySeason)=>void;onReview:()=>void}){
 const [file,setFile]=useState<File|null>(null),[text,setText]=useState(''),[rows,setRows]=useState<RotatingImportRow[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const cancel=useRef<AbortController|null>(null)
 useEffect(()=>()=>cancel.current?.abort(),[])
 const patch=(id:string,p:Partial<RotatingImportRow>)=>{setRows(rows.map(r=>r.id===id?{...r,...p}:r));}
 const weekly=season.school?.pattern==='weekly'
 const find=(value:string)=>{try{const nda=season.school!.cycle.length===6&&/6-Day Schedule/i.test(value),found=weekly?parseWeeklyCollegeSchedule(value,season.start,season.school!.lastClassDate,season.school!.cycle):nda?parseNdaSixDaySchedule(value,season.start,season.school!.lastClassDate):suggestRotatingClasses(value,season.school!.cycle,season.start,season.school!.lastClassDate).map(r=>({...r,include:!!(r.day&&r.label&&r.start&&r.end&&r.end>r.start)&&r.kind==='study'}));setRows(found);setMessage(found.length?'Found '+found.filter(r=>r.kind==='study').length+' classes and '+found.filter(r=>r.kind!=='study').length+' schedule blocks. Check them, then continue to your calendar preview.':'No classes recognized. Try a clearer scan or edit the extracted text below.')}catch(e){setRows([]);setMessage(e instanceof Error?e.message:'Could not recognize this timetable.')}}
 const read=async()=>{if(!file||busy)return;const controller=new AbortController();cancel.current=controller;setBusy(true);setRows([]);setMessage('Reading on this device…');try{const reader=await import('../store/readSchedulePdf');const mode=weekly?'class-table' as const:season.school!.cycle.length===6?'six-day' as const:true;const value=/\.pdf$/i.test(file.name)?await reader.readSchedulePdf(file,1,2,controller.signal,setMessage,false,mode):await reader.readSchedulePhoto(file,controller.signal,setMessage);setText(value);find(value)}catch(e){setMessage(e instanceof Error?e.message:'Could not read.')}finally{setBusy(false)}}
 const add=()=>{
  try{
   change(addTimetableRows(season,rows));setRows([]);setText('');setFile(null);onReview()
  }catch(e){setMessage(e instanceof Error?e.message:'Check the selected classes.')}
 }
 return <details open><summary>Import class timetable · PDF or photo</summary><p>No paid AI. Crop out student email and locker details. Files stay on this device and are not saved. Read up to the first two PDF pages.</p><input aria-label="Class timetable file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]??null);setRows([]);setText('');setMessage('')}}/><button disabled={busy||!file} onClick={()=>void read()}>Read timetable & find classes</button>{busy&&<button onClick={()=>cancel.current?.abort()}>Cancel reading</button>}<p role="status">{message}</p><details><summary>View or correct extracted text</summary><label>Extracted text<textarea maxLength={100000} rows={8} value={text} onChange={e=>{setText(e.target.value);setRows([]);}}/></label><button disabled={busy||!text.trim()} onClick={()=>find(text)}>Find classes again</button></details><p>{weekly?'Dates default to your fall/semester range. KONO reads each weekday, class name, course code, time, building and room, then makes one calendar class for every meeting day.':'Dates default to your selected school year. Confirm each class’s semester dates before saving. In A/E mode, Days 1, 3, 5 become A day and Days 2, 4, 6 become E day. Homeroom is optional; check its meeting days before including it.'}</p>
 {rows.map(r=><article className="wb-record" key={r.id}><label className="wb-check"><input type="checkbox" checked={r.include} onChange={e=>patch(r.id,{include:e.target.checked})}/>Include this class</label><strong>{r.label || 'Unnamed class'}</strong><p>{r.day || (weekly?'Choose weekday':'Choose rotation day')} · {r.start || 'Choose start'}–{r.end || 'Choose end'}{r.location?' · '+r.location:''}</p><details><summary>Edit class, time or semester dates</summary><div className="wb-form-grid"><label>{weekly?'Weekday':'Rotation day'}<select value={r.day} onChange={e=>patch(r.id,{day:e.target.value})}><option value="">{weekly?'Choose weekday':'Choose day from original'}</option>{season.school!.cycle.map(d=><option key={d}>{d}</option>)}</select></label><label>Class name<input maxLength={200} value={r.label} onChange={e=>patch(r.id,{label:e.target.value})}/></label><label>{weekly?'Course code':'Block letter'}<input maxLength={30} value={r.slot} onChange={e=>patch(r.id,{slot:e.target.value})}/></label><label>Building / room<input maxLength={160} value={r.location??''} onChange={e=>patch(r.id,{location:e.target.value})}/></label><label>Starts<input type="time" value={r.start} onInput={e=>patch(r.id,{start:e.currentTarget.value})}/></label><label>Ends<input type="time" value={r.end} onInput={e=>patch(r.id,{end:e.currentTarget.value})}/></label><label>First class date<input type="date" value={r.dateStart} onInput={e=>patch(r.id,{dateStart:e.currentTarget.value})}/></label><label>Last class date<input type="date" value={r.dateEnd} onInput={e=>patch(r.id,{dateEnd:e.currentTarget.value})}/></label><label>Type<select value={r.kind} onChange={e=>patch(r.id,{kind:e.target.value as RotatingImportRow['kind']})}><option value="study">Class</option><option value="break">Free period</option><option value="routine">Advisory / routine</option><option value="hobby">Club / activity</option></select></label></div></details></article>)}
 {!!rows.length&&<button className="primary" disabled={!rows.some(r=>r.include)||busy} onClick={add}>Continue to calendar preview</button>}
 </details>
}
