"""Imports a season's island, one picture per time of day: <season>_sanctuary_morning.png, _noon.png (the
afternoon), _evening.png and _night.png, each 1448 x 1086 and drawn on the regular island's exact footprint
(see docs/seasonal-art-spec.md).

Writes public/garden/terrace-23.0/<folder>/<phase>.webp and <phase>-poster.webp (the small picture shown
while the island loads) and lists them in tools/public-allowlist.json. The folder defaults to the season's
name; give a new one (halloween-v2, …) when replacing pictures people may already have saved, so no browser
keeps showing the old ones. With --moon it also writes src/game/data/<season>Island.ts: where the night
picture's moon is, so the island can glow it.

Run: python3 -I tools/import_season_island.py SEASON SOURCE_DIR [--folder NAME] [--moon]
e.g. python3 -I tools/import_season_island.py halloween SRC --folder halloween-v2 --moon
"""
import json
import os
import sys

import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ISLANDS = os.path.join(ROOT, 'public', 'garden', 'terrace-23.0')
ALLOWLIST = os.path.join(ROOT, 'tools', 'public-allowlist.json')
SOURCES = {'morning': 'morning', 'afternoon': 'noon', 'evening': 'evening', 'night': 'night'}
SIZE = (1448, 1086)


def find_moon(img):
    """The brightest round thing in the top third of the night sky: its center and radius (0..1)."""
    gray = img.convert('L')
    blur = np.asarray(gray.filter(ImageFilter.GaussianBlur(6))).astype(float)
    H, W = blur.shape
    blur[int(H * 0.3):] = 0
    y, x = np.unravel_index(blur.argmax(), blur.shape)
    raw = np.asarray(gray).astype(float)
    yy, xx = np.mgrid[0:H, 0:W]
    ys, xs = np.nonzero((raw > 200) & ((xx - x) ** 2 + (yy - y) ** 2 < 90 ** 2))
    cx, cy = xs.mean(), ys.mean()
    r = np.sqrt((xs - cx) ** 2 + (ys - cy) ** 2).max()
    return {'x': round(float(cx) / W, 4), 'y': round(float(cy) / H, 4), 'r': round(float(r) / W, 4)}


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    folder = sys.argv[sys.argv.index('--folder') + 1] if '--folder' in sys.argv else None
    if folder in args:
        args.remove(folder)
    season, src = args[0], args[1]
    folder = folder or season
    out = os.path.join(ISLANDS, folder)
    os.makedirs(out, exist_ok=True)
    for name in os.listdir(out):
        os.remove(os.path.join(out, name))
    moon = None
    for phase, name in SOURCES.items():
        img = Image.open(os.path.join(src, '%s_sanctuary_%s.png' % (season, name))).convert('RGB')
        if img.size != SIZE:
            raise SystemExit('%s is %s, not %s' % (name, img.size, SIZE))
        img.save(os.path.join(out, phase + '.webp'), 'WEBP', quality=86, method=6)
        img.resize((SIZE[0] // 2, SIZE[1] // 2), Image.LANCZOS).save(os.path.join(out, phase + '-poster.webp'), 'WEBP', quality=70, method=6)
        if phase == 'night' and '--moon' in sys.argv:
            moon = find_moon(img)
    if moon:
        camel = season.split('-')[0] + ''.join(p.title() for p in season.split('-')[1:])
        with open(os.path.join(ROOT, 'src', 'game', 'data', camel + 'Island.ts'), 'w') as f:
            f.write('// Generated by tools/import_season_island.py; do not edit by hand.\n')
            f.write("/** The %s island's full moon in its night picture (0..1 across the map; r is the radius over the\n * map's width), so the island can glow it and send bats past it. */\n" % season)
            f.write('export const %s_MOON=' % season.replace('-', '_').upper() + json.dumps(moon) + ' as const\n')
        print('moon', moon)
    with open(ALLOWLIST) as f:
        files = json.load(f)
    prefix = '/garden/terrace-23.0/%s/' % folder
    files = [p for p in files if not p.startswith(prefix)]
    files += [prefix + '%s%s.webp' % (p, s) for p in SOURCES for s in ('', '-poster')]
    with open(ALLOWLIST, 'w') as f:
        json.dump(files, f, indent=1)
        f.write('\n')


if __name__ == '__main__':
    main()
