"""Imports the October island (the Halloween sanctuary, one picture per time of day) from the provided
source pictures: halloween_sanctuary_morning.png, _noon.png (the afternoon), _evening.png and _night.png,
each 1448 x 1086 and drawn on the regular island's exact footprint.

Writes public/garden/terrace-23.0/halloween-v2/<phase>.webp and <phase>-poster.webp (the small picture shown
while the island loads), and src/game/data/halloweenIsland.ts (where the night picture's moon is, so the
island can glow it).

Run: python3 tools/import_halloween_island.py SOURCE_DIR
(the folder unzipped from 17_halloween_sanctuary_time_of_day_v1.zip)
"""
import json
import os
import sys

import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'public', 'garden', 'terrace-23.0', 'halloween-v2')
TS_OUT = os.path.join(ROOT, 'src', 'game', 'data', 'halloweenIsland.ts')
ALLOWLIST = os.path.join(ROOT, 'tools', 'public-allowlist.json')
SOURCES = {'morning': 'morning', 'afternoon': 'noon', 'evening': 'evening', 'night': 'night'}
SIZE = (1448, 1086)


def find_moon(img):
    """The brightest round thing in the top third of the night sky: its center and radius (0..1)."""
    gray = img.convert('L')
    blur = np.asarray(gray.filter(ImageFilter.GaussianBlur(6))).astype(float)
    H, W = blur.shape
    blur[int(H * 0.3):] = 0
    y, x = np.unravel_index(blur.argmax(), blur.shape)
    raw = np.asarray(gray).astype(float)
    yy, xx = np.mgrid[0:H, 0:W]
    ys, xs = np.nonzero((raw > 200) & ((xx - x) ** 2 + (yy - y) ** 2 < 90 ** 2))
    cx, cy = xs.mean(), ys.mean()
    r = np.sqrt((xs - cx) ** 2 + (ys - cy) ** 2).max()
    return {'x': round(float(cx) / W, 4), 'y': round(float(cy) / H, 4), 'r': round(float(r) / W, 4)}


def main():
    src = sys.argv[1]
    os.makedirs(OUT, exist_ok=True)
    for name in os.listdir(OUT):
        os.remove(os.path.join(OUT, name))
    moon = None
    for phase, name in SOURCES.items():
        img = Image.open(os.path.join(src, 'halloween_sanctuary_%s.png' % name)).convert('RGB')
        if img.size != SIZE:
            raise SystemExit('%s is %s, not %s' % (name, img.size, SIZE))
        img.save(os.path.join(OUT, phase + '.webp'), 'WEBP', quality=86, method=6)
        img.resize((SIZE[0] // 2, SIZE[1] // 2), Image.LANCZOS).save(os.path.join(OUT, phase + '-poster.webp'), 'WEBP', quality=70, method=6)
        if phase == 'night':
            moon = find_moon(img)
    with open(TS_OUT, 'w') as f:
        f.write('// Generated by tools/import_halloween_island.py; do not edit by hand.\n')
        f.write("/** The October island's full moon in its night picture (0..1 across the map; r is the radius over the\n * map's width), so the island can glow it and send bats past it. */\n")
        f.write('export const HALLOWEEN_MOON=' + json.dumps(moon) + ' as const\n')
    with open(ALLOWLIST) as f:
        files = json.load(f)
    files = [p for p in files if not p.startswith('/garden/terrace-23.0/halloween-v2/')]
    files += ['/garden/terrace-23.0/halloween-v2/%s%s.webp' % (p, s) for p in SOURCES for s in ('', '-poster')]
    with open(ALLOWLIST, 'w') as f:
        json.dump(files, f, indent=1)
        f.write('\n')
    print('moon', moon)


if __name__ == '__main__':
    main()
