// Actual application functions with isolated fixtures; no browser or user-data writes.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript')
const root=path.resolve(__dirname,'..'),cache=new Map(),{randomUUID}=require('node:crypto')
function load(relative){
 const file=path.resolve(root,relative)
 if(cache.has(file))return cache.get(file).exports
 const module={exports:{}};cache.set(file,module)
 const requireLocal=name=>name.endsWith('.css')?{}:name.startsWith('.')?load(path.resolve(path.dirname(file),name+(path.extname(name)?'':fs.existsSync(path.resolve(path.dirname(file),name+'.ts'))?'.ts':'.tsx'))):require(name)
 vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,{module,exports:module.exports,require:requireLocal,Date,Intl,Set,Map,Math,structuredClone,crypto:{randomUUID},console})
 return module.exports
}


const model=load('src/store/model.ts'),{academicTemplate,refreshAcademicTemplate}=load('src/store/academicCatalog.ts'),{classOccurrences,nextClassDate}=load('src/store/classSchedule.ts'),{schoolDay}=load('src/store/schoolCalendar.ts'),{addWeeklyClass,weeklyClassDates,weeklyConflicts}=load('src/store/weeklyClass.ts')
let n=0
function test(title,f){f();n++;console.log('PASS '+title)}
const input={title:'Biology',subjectId:'',weekdays:[1,3],start:'10:00',end:'12:00',first:'2026-09-01',last:'2026-09-30',location:'Room 1'}
test('Manual weekly creates subjects and all sessions, retaining other schedules',()=>{const d=model.createFreshData(),next=addWeeklyClass(d,d.activeProfileId,input);assert.equal(next.subjects.length,1);assert.equal(next.studySeasons.length,d.studySeasons.length+1);assert.equal(weeklyClassDates(input).length,9);assert.equal(classOccurrences(next,'2026-09-02')[0].block.label,'Biology');assert.equal(classOccurrences(next,'2026-09-03').length,0);assert.equal(d.subjects.length,0)})
test('Next-class reminder uses the next selected weekday',()=>{const d=model.createFreshData(),next=addWeeklyClass(d,d.activeProfileId,input);assert.equal(nextClassDate(classOccurrences(next,'2026-09-02')[0]),'2026-09-07');assert.equal(nextClassDate(classOccurrences(next,'2026-09-07')[0]),'2026-09-09')})
test('Manual duplicates, missing weekdays, invalid times and foreign subjects rejected',()=>{const d=model.createFreshData(),next=addWeeklyClass(d,d.activeProfileId,input);assert.throws(()=>addWeeklyClass(next,d.activeProfileId,input,true),/already/);assert.throws(()=>weeklyClassDates({...input,weekdays:[]}));assert.throws(()=>weeklyClassDates({...input,end:'09:00'}));assert.throws(()=>addWeeklyClass(d,'foreign',input));assert.throws(()=>addWeeklyClass(d,d.activeProfileId,{...input,subjectId:'foreign'}))})
test('Overlaps require explicit acknowledgement',()=>{const d=model.createFreshData(),next=addWeeklyClass(d,d.activeProfileId,input),other={...input,title:'Chemistry',start:'11:00',end:'13:00'};assert.equal(weeklyConflicts(next,other).length,9);assert.throws(()=>addWeeklyClass(next,d.activeProfileId,other),/overlaps/);assert.equal(addWeeklyClass(next,d.activeProfileId,other,true).subjects.length,2)})
function college(term){const d=model.createFreshData(),s=academicTemplate(d.activeProfileId,term);s.school.program='Arts';d.studySeasons=[s];for(const day of ['Monday','Tuesday','Wednesday','Thursday','Friday'])s.week[day]=[{id:day,label:day+' course',kind:'study',start:'10:00',end:'11:00',fullYear:true}];return {d,s}}
test('McGill Fall Dec 3 replaces Thursday with Monday, without shifting Friday',()=>{const {d,s}=college('mcgill-fall-2026');assert.equal(classOccurrences(d,'2026-12-03')[0].block.label,'Monday course');assert.equal(classOccurrences(d,'2026-12-04')[0].block.label,'Friday course');assert.equal(schoolDay(s,'2026-12-03').cycleDay,'Monday')})
test('McGill reading break, election cancellation and exam period suppress normal classes',()=>{const {d}=college('mcgill-fall-2026');for(const date of ['2026-09-07','2026-10-05','2026-10-09','2026-10-14','2026-12-07'])assert.equal(classOccurrences(d,date).length,0);assert.equal(classOccurrences(d,'2026-10-15')[0].block.label,'Thursday course')})
test('Winter makeup Tuesdays and Wednesdays use Friday and Monday respectively',()=>{const {d}=college('mcgill-winter-2027');assert.equal(classOccurrences(d,'2027-04-13')[0].block.label,'Friday course');assert.equal(classOccurrences(d,'2027-04-14')[0].block.label,'Monday course');assert.equal(classOccurrences(d,'2027-04-15').length,0)})
test('Catalog data is cloned per student, with source version preserved',()=>{const {d,s}=college('mcgill-fall-2026');const other=academicTemplate('other','mcgill-fall-2026');s.school.exceptions[0].label='My correction';assert.notEqual(other.school.exceptions[0].label,'My correction');const saved=model.normalizeData(d);assert.equal(saved.schemaVersion,6);assert.equal(saved.studySeasons[0].school.pattern,'weekly');assert.equal(saved.studySeasons[0].school.catalogRevision,'2026-09-09')})
test('Catalog refresh preserves classes and custom exceptions in a reviewable copy',()=>{const {s}=college('mcgill-fall-2026');s.school.exceptions.push({id:'personal',start:'2026-11-10',end:'2026-11-10',kind:'notice',label:'Personal event',audience:'all'});const result=refreshAcademicTemplate(s);assert.equal(result.week.Monday[0].id,'Monday');assert.ok(result.school.exceptions.some(e=>e.id==='personal'));assert.notEqual(result,s)})
test('Invalid weekly calendar pattern rejected on server normalization',()=>{const {d,s}=college('mcgill-fall-2026');s.school.cycle=['A day','E day'];assert.throws(()=>model.normalizeData(d),/seven weekdays/)})
test('Work can have different Monday and Tuesday hours without creating school subjects',()=>{const d=model.createFreshData(),m={...input,title:'Work',subjectId:'',activity:true,weekdays:[1],start:'08:00',end:'16:00'},a=addWeeklyClass(d,d.activeProfileId,m),b=addWeeklyClass(a,d.activeProfileId,{...m,weekdays:[2],start:'09:00',end:'15:00'});assert.equal(b.subjects.length,0);assert.equal(classOccurrences(b,'2026-09-07')[0].block.start,'08:00');assert.equal(classOccurrences(b,'2026-09-08')[0].block.end,'15:00');assert.equal(classOccurrences(b,'2026-09-08')[0].block.label,'Work');assert.equal(classOccurrences(b,'2026-09-08')[0].block.kind,'routine')})
test('New plans start without an empty default schedule',()=>{const d=model.createFreshData();assert.equal(d.studySeasons.length,0);assert.equal(model.normalizeData(d).studySeasons.length,0)})
console.log(n+' three-flow schedule test groups passed.')
