// Actual application functions with isolated fixtures; no browser or user-data writes.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript')
const root=path.resolve(__dirname,'..'),cache=new Map(),{randomUUID}=require('node:crypto')
function load(relative){
 const file=path.resolve(root,relative)
 if(cache.has(file))return cache.get(file).exports
 const module={exports:{}};cache.set(file,module)
 const requireLocal=name=>name.endsWith('.css')?{}:name.startsWith('.')?load(path.resolve(path.dirname(file),name+(path.extname(name)?'':fs.existsSync(path.resolve(path.dirname(file),name+'.ts'))?'.ts':'.tsx'))):require(name)
 vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,{module,exports:module.exports,require:requireLocal,Date,Intl,Set,Map,Math,structuredClone,crypto:{randomUUID},console})
 return module.exports
}


const model=load('src/store/model.ts'),{schoolDay,validateSchool}=load('src/store/schoolCalendar.ts'),{schoolPreset}=load('src/store/schoolPresets.ts'),{classOccurrences,nextClassDate,saveClassNote}=load('src/store/classSchedule.ts'),{suggestSchoolDates,suggestRotatingClasses,parseWeeklyCollegeSchedule,addTimetableRows}=load('src/store/schoolImport.ts'),{mergeData}=load('src/store/merge.ts')
const {buildElevatorWeek,hanoverElevatorCycle,parseHanoverElevatorCourses}=load('src/store/elevatorSchedule.ts')
let passed=0
function test(name,fn){fn();passed++;console.log('PASS '+name)}
function fixture(type='blank'){
 const data=model.createFreshData(),s=schoolPreset(data.activeProfileId,type);s.school.anchorDay=s.school.cycle[0];s.school.grade='11';data.studySeasons=[s];return {data,s}
}
const rule=(start,kind='holiday',end=start)=>({id:randomUUID(),start,end,kind,label:kind,audience:'all'})
test('A/E alternates over school days, not weekdays',()=>{const {s}=fixture();assert.equal(schoolDay(s,'2026-09-02').cycleDay,'A day');assert.equal(schoolDay(s,'2026-09-03').cycleDay,'E day');assert.equal(schoolDay(s,'2026-09-05').closed,true);assert.equal(schoolDay(s,'2026-09-07').cycleDay,'E day')})
test('Holiday pauses; snow consumes the canceled turn',()=>{const {s}=fixture();s.school.exceptions=[rule('2026-09-03')];assert.equal(schoolDay(s,'2026-09-04').cycleDay,'E day');const snow=structuredClone(s);snow.school.exceptions=[rule('2026-09-03','snow')];assert.equal(schoolDay(snow,'2026-09-03').closed,true);assert.equal(schoolDay(snow,'2026-09-04').cycleDay,'A day');const paused=structuredClone(snow);paused.school.snowAdvances=false;assert.equal(schoolDay(paused,'2026-09-04').cycleDay,'E day')})
test('Holiday weekend does not double count closed days',()=>{const {s}=fixture('marshfield');assert.equal(schoolDay(s,'2026-09-08').cycleDay,'A day')})
test('Known anchor can start in the middle of the year',()=>{const {s}=fixture();s.school.anchorDate='2026-09-04';s.school.anchorDay='A day';assert.equal(schoolDay(s,'2026-09-02').cycleDay,'A day');assert.equal(schoolDay(s,'2026-09-03').cycleDay,'E day');assert.equal(schoolDay(s,'2026-09-04').cycleDay,'A day')})
test('School correction resets following days and weekend makeup advances',()=>{const {s}=fixture();s.school.exceptions=[{...rule('2026-09-05','makeup'),cycleDay:'A day'}];assert.equal(schoolDay(s,'2026-09-05').cycleDay,'A day');assert.equal(schoolDay(s,'2026-09-07').cycleDay,'E day')})
test('Both supplied school templates validate without student personal information',()=>{for(const type of ['marshfield','nda']){const {s,data}=fixture(type);validateSchool(s.school,s.start,s.end);assert.equal(model.normalizeData(data).studySeasons[0].school.name,s.school.name);assert.ok(!JSON.stringify(s).includes('@'));assert.ok(!JSON.stringify(s).includes('locker'))}})
test('NDA Day 2 and Day 5 remain distinct',()=>{const {s,data}=fixture('nda');s.week['Day 2']=[{id:'advisory',label:'Advisory',start:'09:56',end:'10:23',kind:'routine'}];s.week['Day 5']=[{id:'club',label:'Clubs',start:'09:56',end:'10:23',kind:'hobby'}];assert.equal(classOccurrences(data,'2026-09-10')[0].block.label,'Advisory');assert.equal(classOccurrences(data,'2026-09-15')[0].block.label,'Clubs')})
test('Senior-only closure does not close grade 11',()=>{const {s}=fixture('nda');assert.equal(schoolDay(s,'2027-05-17').closed,false);const senior=structuredClone(s);senior.school.grade='12';assert.equal(schoolDay(senior,'2027-05-17').closed,true)})
test('Last regular classes differs from final exams and teacher days',()=>{const {s}=fixture('nda');assert.equal(schoolDay(s,'2027-06-03').closed,true);assert.equal(schoolDay(s,'2027-06-04').closed,false);assert.equal(schoolDay(s,'2027-06-10').closed,true)})
test('Half-day times are flagged until confirmed; notes use original block',()=>{const {data,s}=fixture();s.school.exceptions=[rule('2026-09-02','half')];s.week['A day']=[{id:'b',slot:'A',label:'Biology',start:'08:00',end:'09:24',kind:'study'}];assert.equal(classOccurrences(data,'2026-09-02')[0].timePending,true);const confirmed=structuredClone(data);confirmed.studySeasons[0].school.exceptions[0].bells={A:{start:'08:00',end:'08:40'}};const item=classOccurrences(confirmed,'2026-09-02')[0];assert.equal(item.displayEnd,'08:40');assert.equal(item.block.end,'09:24');assert.equal(item.timePending,false);const saved=saveClassNote(confirmed,item,'Bring book');assert.equal(saved.studySeasons[0].week['A day'][0].occurrenceNotes['2026-09-02'],'Bring book')})
test('Exam days never invent normal classes without an exam bell assignment',()=>{const {data,s}=fixture();s.school.exceptions=[rule('2026-09-02','exam')];s.week['A day']=[{id:'b',slot:'A',label:'Biology',start:'08:00',end:'09:24',kind:'study'}];assert.equal(classOccurrences(data,'2026-09-02').length,0)})
test('Semester replacements and next-class reminders follow actual rotation',()=>{const {data,s}=fixture();s.week['A day']=[{id:'health',label:'Health',start:'08:00',end:'09:24',kind:'study',dateStart:'2026-09-02',dateEnd:'2026-09-03'},{id:'art',label:'Art',start:'08:00',end:'09:24',kind:'study',dateStart:'2026-09-04',dateEnd:'2027-06-17'}];assert.equal(classOccurrences(data,'2026-09-02')[0].block.label,'Health');assert.equal(classOccurrences(data,'2026-09-04')[0].block.label,'Art');assert.equal(nextClassDate(classOccurrences(data,'2026-09-04')[0]),'2026-09-08');assert.equal(nextClassDate(classOccurrences(data,'2026-09-02')[0]),undefined)})
test('No classes outside year, inactive school or foreign profile',()=>{const {data,s}=fixture();s.week['A day']=[{id:'b',label:'Biology',start:'08:00',end:'09:00',kind:'study'}];assert.equal(classOccurrences(data,'2026-08-31').length,0);s.active=false;assert.equal(classOccurrences(data,'2026-09-02').length,0);s.active=true;data.activeProfileId='foreign';assert.equal(classOccurrences(data,'2026-09-02').length,0)})
test('Reject invalid anchor, conflicting rules, malformed times and long years',()=>{const {s}=fixture();for(const mutate of [c=>c.anchorDay='',c=>c.anchorDate='2026-09-05',c=>c.exceptions=[rule('2026-09-03'),rule('2026-09-03','snow')],c=>c.exceptions=[{...rule('2026-09-03','half'),bells:{A:{start:'09:00',end:'08:00'}}}]]){const c=structuredClone(s.school);mutate(c);assert.throws(()=>validateSchool(c,s.start,s.end))}assert.throws(()=>validateSchool(s.school,s.start,'2030-06-01'))})
test('Quarter notice does not override half-day rule',()=>{const {s}=fixture('nda');const d=schoolDay(s,'2027-04-02');assert.equal(d.special,true);assert.match(d.label,/quarter 3/)})
test('School data survives backup normalization and independent edits merge',()=>{const {data}=fixture();const b=model.normalizeData(data),l=structuredClone(b),r=structuredClone(b);l.studySeasons[0].school.exceptions.push(rule('2026-10-01'));r.studySeasons[0].school.exceptions.push(rule('2026-10-02'));const m=mergeData(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.data.studySeasons[0].school.exceptions.length,2)})
test('Calendar OCR yields unchecked cross-year and reverse-date suggestions',()=>{const rows=suggestSchoolDates('Dec 21 – Jan 3 Christmas Break (No School)\n15 - 19 FEBRUARY VACATION\nMay 17 Senior Reading Day (No School)','2026-09-01','2027-06-30');assert.equal(rows.length,3);assert.ok(rows.every(r=>!r.include));assert.equal(rows[0].start,'2026-12-21');assert.equal(rows[0].end,'2027-01-03');assert.equal(rows[1].start,'2027-02-15');assert.equal(rows[1].end,'2027-02-19');assert.equal(rows[2].audience,'seniors')})
test('Timetable OCR refuses guessed AM/PM or grid columns',()=>{const rows=suggestRotatingClasses('Biology\n7:50 - 8:50 (Period A)\nDay 2\nEnglish 1:00pm - 2:00pm (Period G)',['Day 1','Day 2'],'2026-09-01','2027-06-01');assert.equal(rows.length,2);assert.equal(rows[0].day,'');assert.equal(rows[0].start,'');assert.equal(rows[1].day,'Day 2');assert.equal(rows[1].start,'13:00');assert.ok(rows.every(r=>!r.include))})
test('Weekly college PDF table becomes weekday semester classes with locations',()=>{const text='Weekly Class Schedule\nCourse | Class Name | Day | Time | Building | Room\nPSYC 305-001 | Statistics for Experimental Design | Monday & Wednesday | 10:05 AM - 11:25 AM | Adams Building | AUD\nPSYC 213-001 | Cognition | Tuesday & Thursday | 1:05 PM - 2:25 PM | Macdonald-Harrington Building | G-10\nPSYC 444-001 | Sleep Mechanisms and Behaviour | Monday & Wednesday | 2:35 PM - 3:55 PM | McIntyre Medical Building | 522\nPHIL 306-001 | Philosophy of Mind | Tuesday & Thursday | 4:05 PM - 5:25 PM | Burnside Hall | 1B45\nPSYC 337-001 | Introduction to Psychopathology | Monday & Wednesday | 4:35 PM - 5:55 PM | Adams Building | AUD',cycle=['Monday','Tuesday','Wednesday','Thursday','Friday'],rows=parseWeeklyCollegeSchedule(text,'2026-09-01','2026-12-15',cycle);assert.equal(rows.length,10);assert.ok(rows.every(r=>r.include&&r.kind==='study'));assert.equal(rows[0].day,'Monday');assert.equal(rows[1].day,'Wednesday');assert.equal(rows[2].start,'13:05');assert.equal(rows[2].end,'14:25');assert.equal(rows[0].label,'PSYC 305-001 · Statistics for Experimental Design');assert.equal(rows[0].location,'Adams Building AUD');const {s}=fixture('weekly');s.start='2026-09-01';s.end='2026-12-15';s.school.lastClassDate='2026-12-15';s.school.cycle=cycle;s.week=Object.fromEntries(cycle.map(day=>[day,[]]));const ready=addTimetableRows(s,rows);assert.equal(ready.week.Monday.length,3);assert.equal(ready.week.Tuesday.length,2);assert.equal(ready.week.Monday[0].location,'Adams Building AUD');assert.equal(ready.week.Thursday[1].label,'PHIL 306-001 · Philosophy of Mind')})
test('Full-year classes follow announced makeup dates, semester classes do not',()=>{const {data,s}=fixture();s.end='2027-06-21';s.school.exceptions=[rule('2027-06-21','makeup')];s.week['A day']=[{id:'fy',label:'Full year',fullYear:true,start:'08:00',end:'09:00',kind:'study',dateEnd:'2027-06-17'},{id:'s1',label:'Semester only',start:'09:00',end:'10:00',kind:'study',dateEnd:'2027-06-17'}];s.school.exceptions[0].cycleDay='A day';assert.equal(classOccurrences(data,'2027-06-21').length,1);assert.equal(classOccurrences(data,'2027-06-21')[0].block.id,'fy')})
test('Hanover template validates and follows all 14 elevator days',()=>{const {s}=fixture('hanover');validateSchool(s.school,s.start,s.end);assert.equal(s.school.pattern,'elevator');assert.deepEqual(Array.from(s.school.cycle),Array.from(hanoverElevatorCycle));assert.equal(schoolDay(s,'2026-08-31').cycleDay,'1A');assert.equal(schoolDay(s,'2026-09-01').cycleDay,'2B');assert.equal(schoolDay(s,'2026-09-08').cycleDay,'5A')})
test('Elevator builder rotates seven courses and assigns fifth-block lunch',()=>{const courses=Array.from({length:7},(_,i)=>({label:'Course '+(i+1),location:'Room '+(i+1),lunchWave:(i%3)+1})),week=buildElevatorWeek(courses);assert.equal(Object.keys(week).length,14);assert.equal(JSON.stringify(week['1A'].filter(b=>b.kind==='study').map(b=>b.label)),JSON.stringify(['Course 1','Course 2','Course 3','Course 7','Course 5','Course 6','Course 4']));assert.equal(week['2B'].filter(b=>b.kind==='study')[0].label,'Course 2');assert.equal(week['1A'].find(b=>b.kind==='break').label,'Lunch 2');assert.equal(week['7B'].filter(b=>b.kind==='study').length,7)})
test('Elevator builder reports missing scanned rows without crashing',()=>{const courses=Array.from({length:7},(_,i)=>({label:'Course '+(i+1),location:'Room '+(i+1),lunchWave:1}));courses[3]=undefined;assert.throws(()=>buildElevatorWeek(courses),/Course 4 is missing/)})
test('Elevator builder reports blank scanned course rows without raw label errors',()=>{const courses=Array.from({length:7},(_,i)=>({label:'Course '+(i+1),location:'Room '+(i+1),lunchWave:1}));courses[2]={label:'',location:'',lunchWave:1};assert.throws(()=>buildElevatorWeek(courses),/Course 3 needs a class name/);assert.doesNotThrow(()=>buildElevatorWeek(courses.map((course,i)=>i===2?{...course,label:'Course 3'}:course)))})
test('Hanover PDF course key fills seven editable courses without student header',()=>{const text='Student Name - Schedule Reference\nCourse Key\nNo.\nClass\nTeacher\nRoom\nCourse Code\nLunch if in 5th Block\n'+Array.from({length:7},(_,i)=>`${i+1}\nCourse ${i+1}\nTeacher Name\nHS${300+i}\n${400+i}-01\nLunch ${(i%3)+1}`).join('\n')+'\nBlock\nTime';const rows=parseHanoverElevatorCourses(text);assert.equal(rows.length,7);assert.equal(rows[0].label,'Course 1');assert.equal(rows[1].lunchWave,2);assert.match(rows[6].location,/HS306/);assert.ok(!JSON.stringify(rows).includes('Student Name'))})
test('Hanover two-page grid reconstructs the seven base courses and lunch waves',()=>{const order=[1,2,3,7,5,6,4],block=(slot,n,lunch)=>`${slot} | ${slot}:00-${slot}:45\nCourse ${n}\nTeacher ${n}\nHS30${n} | 40${n}-01${lunch?`\nLunch ${lunch}: 11:23-11:52`:''}`,grid='14-Day Elevator Schedule - Page 1\n1A\n'+order.map((n,i)=>block(i+1,n,i===4?2:0)).join('\n')+'\n'+[["2B",6,1],["3A",4,3],["4B",1,2],["5A",2,3],["6B",3,1],["7A",7,2]].map(([d,n,l])=>`${d}\n${block(5,n,l)}`).join('\n');const rows=parseHanoverElevatorCourses(grid);assert.equal(rows.length,7);assert.equal(rows[0].label,'Course 1');assert.equal(rows[3].label,'Course 4');assert.equal(rows[4].lunchWave,2);assert.equal(rows[3].lunchWave,3)})
console.log(passed+' school-calendar regression groups passed. No user data changed.')
